import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import journalCss from "../journal-migration.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { AppShell } from "@/components/AppShell";
import { AppStateProvider } from "@/state/app-state";
import { ExamCompletionBridge } from "@/components/ExamCompletionBridge";
import { ExamVocabularyBridge } from "@/components/ExamVocabularyBridge";
import { ListeningRealAudioBridge } from "@/components/ListeningRealAudioBridge";
import { Toaster } from "@/components/ui/sonner";
function NotFoundComponent(){return <div className="journal-app journal-canvas flex min-h-screen items-center justify-center px-4"><div className="journal-grid w-full max-w-md border border-[var(--journal-line)] p-8 text-center shadow-[5px_6px_0_rgba(63,99,242,.10)]"><p className="display text-7xl text-[var(--journal-ink)]">404</p><h2 className="display mt-4 text-xl text-[var(--journal-ink)]">Page not found</h2><p className="mt-2 text-sm text-[#63709A]">The page you're looking for doesn't exist or has been moved.</p><div className="mt-6"><Link to="/" className="journal-button inline-flex items-center justify-center px-4 py-2 text-sm font-medium">Go home</Link></div></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){console.error(error);const router=useRouter();useEffect(()=>{reportLovableError(error,{boundary:"tanstack_root_error_component"})},[error]);return <div className="journal-app journal-canvas flex min-h-screen items-center justify-center px-4"><div className="journal-ledger w-full max-w-md border border-[var(--journal-line)] bg-[var(--journal-yellow)] p-8 text-center shadow-[5px_6px_0_rgba(255,93,177,.08)]"><h1 className="display text-xl text-[var(--journal-ink)]">This page didn't load</h1><p className="mt-2 text-sm text-[#63709A]">Something went wrong on our end. You can try refreshing or head back home.</p><div className="mt-6 flex flex-wrap justify-center gap-2"><button onClick={()=>{router.invalidate();reset()}} className="journal-button inline-flex items-center justify-center px-4 py-2 text-sm font-medium">Try again</button><a href="/" className="inline-flex items-center justify-center border border-[var(--journal-blue)] bg-[var(--journal-paper)] px-4 py-2 text-sm font-medium text-[var(--journal-ink)]">Go home</a></div></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{title:"Ivy English"},{name:"description",content:"Ivy 的英语与 IELTS 学习空间。"},{name:"author",content:"Ivy"},{property:"og:title",content:"Ivy English"},{property:"og:description",content:"Ivy 的英语与 IELTS 学习空间。"},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"},{name:"twitter:site",content:"@Lovable"}],links:[{rel:"stylesheet",href:appCss},{rel:"stylesheet",href:journalCss},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=Caveat:wght@500;600&family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&family=Manrope:wght@300;400;500;600&family=Noto+Sans+SC:wght@300;400;500&display=swap"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();useEffect(()=>{function closeExamPopoverOnOutsidePointer(event:PointerEvent){if(window.location.pathname!=="/exam")return;const openToggle=document.querySelector<HTMLButtonElement>('button[aria-expanded="true"]');if(!openToggle)return;const container=openToggle.parentElement;const target=event.target as Node|null;if(!container||!target||container.contains(target))return;openToggle.click()}document.addEventListener("pointerdown",closeExamPopoverOnOutsidePointer,true);return()=>document.removeEventListener("pointerdown",closeExamPopoverOnOutsidePointer,true)},[]);return <QueryClientProvider client={queryClient}><AppStateProvider><ExamCompletionBridge/><ExamVocabularyBridge/><ListeningRealAudioBridge/><AppShell><Outlet/></AppShell><Toaster/></AppStateProvider></QueryClientProvider>}
