import { useMemo, useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { BookMarked, Check, ChevronDown, ChevronUp, FileText, Info, Plus, Search, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Callout, Chip, PageHeader, SectionTitle, StatusPill } from "@/components/ui-kit";
import { IndexCard, JournalPaper, StickyNote } from "@/components/journal-ui";
import { useAppState } from "@/state/app-state";
import { cambridgeBooks } from "@/data/mock";
import type { Question } from "@/data/mock";
import { cn } from "@/lib/utils";

type TabKey="recent"|"cambridge"|"official"|"personal";
type Subject="listening"|"speaking"|"reading"|"writing";
export const Route=createFileRoute("/bank")({validateSearch:(search:Record<string,unknown>):{tab:TabKey;subject:string}=>{const tabs:TabKey[]=["recent","cambridge","official","personal"];const subjects=["全部","口语","写作","阅读","听力"];return{tab:tabs.includes(search.tab as TabKey)?search.tab as TabKey:"recent",subject:subjects.includes(search.subject as string)?search.subject as string:"全部"}},head:()=>({meta:[{title:"题库 · Ivy English"},{name:"description",content:"近期考场回忆、剑雅、官方样题和我的材料。"}]}),component:BankPage});
const tabLabels:{key:TabKey;label:string}[]=[{key:"recent",label:"近期考场题"},{key:"cambridge",label:"剑雅"},{key:"official",label:"官方"},{key:"personal",label:"我的题库"}];
const subjectByModule:Record<string,Subject>={听力:"listening",口语:"speaking",阅读:"reading",写作:"writing"};
const themeByModule:Record<string,string>={听力:"subject-listening",口语:"subject-speaking",阅读:"subject-reading",写作:"subject-writing"};

function QuestionCard({q,onPractice}:{q:Question;onPractice:()=>void}){const practiced=q.practiceCount>0;const [noteOpen,setNoteOpen]=useState(false);const subject=subjectByModule[q.module]??"reading";return <StickyNote subject={subject} className="flex h-full flex-col p-5 pt-7"><div className="flex items-start justify-between gap-3"><p className="text-sm leading-relaxed text-[var(--journal-ink)]">{q.title}</p><StatusPill status={q.status}/></div><div className="mt-3 flex flex-wrap gap-1.5">{q.topic.map(t=><span key={t} className="border border-[var(--journal-line)] bg-[var(--journal-paper)] px-2 py-0.5 text-[10px] text-[#63709A]">{t}</span>)}</div><div className="mt-5 grid grid-cols-2 gap-3 text-[11px] text-[#63709A]">{q.recentDate?<div><p>最近出现</p><p className="mt-0.5 tabular-nums text-[var(--journal-ink)]">{q.recentDate}</p></div>:null}{q.reportCount?<div><p>报告</p><p className="mt-0.5 tabular-nums text-[var(--journal-ink)]">{q.reportCount} 次</p></div>:null}</div>{q.note?<div className="mt-5 border-t border-[color:var(--journal-line)] pt-4"><button type="button" onClick={()=>setNoteOpen(v=>!v)} className="flex w-full items-center gap-2 text-left text-[11px] text-[#63709A]"><span className="shrink-0 text-[var(--journal-ink)]">思路备忘</span>{!noteOpen?<span className="min-w-0 flex-1 truncate">{q.note}</span>:<span className="flex-1"/>}{noteOpen?<ChevronUp className="size-3.5"/>:<ChevronDown className="size-3.5"/>}</button>{noteOpen?<p className="journal-ledger mt-2 border border-[var(--journal-line)] bg-[var(--journal-paper)] px-3 py-2 text-xs leading-6 text-[#52608C]">{q.note}</p>:null}</div>:null}<div className="mt-auto flex items-center gap-3 pt-6"><Button asChild size="sm" variant="outline" className="rounded-sm border-[var(--subject-color)] bg-[var(--journal-paper)]"><Link to="/question" search={{id:q.id}}>查看并开始</Link></Button><button type="button" onClick={onPractice} className={cn("inline-flex items-center gap-1 text-[11px]",practiced?"text-[#4AA934]":"text-[#63709A]")}><Check className="size-3"/>标记已练习</button></div></StickyNote>}
function moduleHref(module:string){if(module==="Reading")return "/exam-v3?mode=familiarisation&scope=full";if(module==="Listening")return "/listening-exam-v3?mode=familiarisation&scope=full";if(module==="Writing")return "/writing-exam-v2?mode=familiarisation&scope=full";return "/speaking-workspace?mode=full"}
function officialHref(module:string){if(module==="阅读")return "/exam-v3?mode=familiarisation&scope=passage";if(module==="听力")return "/listening-exam-v3?mode=familiarisation&scope=section";if(module==="写作")return "/writing-exam-v2?mode=familiarisation&scope=task1";return "/speaking-workspace?mode=part1"}
function withinPeriod(date:string|undefined,period:string){if(!date)return true;const days=period==="本月"?31:period==="近 3 个月"?90:120;const value=new Date(`${date}T00:00:00`).getTime();return Number.isFinite(value)&&value>=Date.now()-days*86400000}
function BankPage(){const {tab,subject}=Route.useSearch();const navigate=useNavigate({from:Route.fullPath});const {questions,markPracticed,libraryItems,mistakes,vocabulary}=useAppState();const [period,setPeriod]=useState("本季");const [sort,setSort]=useState("最近出现");const [query,setQuery]=useState("");const [openBook,setOpenBook]=useState<string|null>("c18");const recent=useMemo(()=>{let list=questions.filter(q=>q.sourceType==="recent"&&withinPeriod(q.recentDate,period));if(subject!=="全部")list=list.filter(q=>q.module===subject);const normalized=query.trim().toLowerCase();if(normalized)list=list.filter(q=>[q.title,q.part??"",q.module,...q.topic,q.note??""].some(value=>value.toLowerCase().includes(normalized)));if(sort==="报告次数")list=[...list].sort((a,b)=>(b.reportCount??0)-(a.reportCount??0));else if(sort==="我还没练")list=list.filter(q=>q.practiceCount===0);else list=[...list].sort((a,b)=>(b.recentDate??"").localeCompare(a.recentDate??""));return list},[questions,subject,sort,query,period]);const speakingByPart=(part:string)=>recent.filter(q=>q.module==="口语"&&q.part===part);const writing=recent.filter(q=>q.module==="写作");const others=recent.filter(q=>q.module==="阅读"||q.module==="听力");const personal=[{title:"我的材料",hint:"PDF · 链接 · 笔记",count:libraryItems.length,to:"/library"},{title:"错题",hint:"Reading · Listening",count:mistakes.length,to:"/mistakes"},{title:"生词本",hint:"真实语境中遇到的词",count:vocabulary.length,to:"/vocabulary"},{title:"待复习",hint:"还没有标记掌握",count:mistakes.filter(m=>m.status!=="已掌握").length,to:"/mistakes"}];
return <div className="journal-page space-y-9"><PageHeader title="题库" subtitle="官方题目、剑雅、近期考场回忆和你自己的材料，都在这里。"/><div className="journal-tabs">{tabLabels.map(t=><button key={t.key} type="button" onClick={()=>navigate({search:{tab:t.key,subject}})} className="journal-tab" data-active={tab===t.key}>{t.label}</button>)}</div>
{tab==="recent"?<div className="space-y-9"><Callout><span className="flex gap-2"><Info className="mt-0.5 size-3.5 shrink-0"/>这些题目来自考生考后回忆整理，不代表 IELTS 官方题目，也不用于预测押题。</span></Callout><div className="journal-section-paper space-y-3 p-4"><div className="relative max-w-md"><Search className="pointer-events-none absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-[#63709A]"/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索题目、话题或标签..." className="h-9 w-full border border-[var(--journal-line)] bg-[var(--journal-paper)] pl-9 pr-4 text-xs outline-none"/></div><div className="flex items-center gap-2 overflow-x-auto"><span className="text-[11px] text-[#63709A]">科目</span>{["全部","口语","写作","阅读","听力"].map(s=><Chip key={s} active={subject===s} onClick={()=>navigate({search:{tab:"recent",subject:s}})}>{s}</Chip>)}</div><div className="flex items-center gap-2 overflow-x-auto"><span className="text-[11px] text-[#63709A]">时间</span>{["本月","近 3 个月","本季"].map(p=><Chip key={p} active={period===p} onClick={()=>setPeriod(p)}>{p}</Chip>)}</div><div className="flex items-center gap-2 overflow-x-auto"><span className="text-[11px] text-[#63709A]">排序</span>{["最近出现","报告次数","我还没练"].map(s=><Chip key={s} active={sort===s} onClick={()=>setSort(s)}>{s}</Chip>)}</div></div>{(subject==="全部"||subject==="口语")?<section className="space-y-8"><SectionTitle title="Speaking · 近期回忆" subtitle={`时间范围：${period}`}/>{["Part 1","Part 2","Part 3"].map(part=>{const list=speakingByPart(part);return list.length?<div key={part}><p className="mb-3 text-xs text-[#63709A]">{part}</p><div className="grid gap-4 md:grid-cols-2">{list.map(q=><QuestionCard key={q.id} q={q} onPractice={()=>markPracticed(q.id)}/>)}</div></div>:null})}</section>:null}{(subject==="全部"||subject==="写作")&&writing.length?<section><SectionTitle title="Writing · 近期考题"/><div className="grid gap-4 md:grid-cols-2">{writing.map(q=><QuestionCard key={q.id} q={q} onPractice={()=>markPracticed(q.id)}/>)}</div></section>:null}{(subject==="全部"||subject==="阅读"||subject==="听力")&&others.length?<section><SectionTitle title="Reading & Listening · 近期题型"/><div className="grid gap-4 md:grid-cols-2">{others.map(q=><QuestionCard key={q.id} q={q} onPractice={()=>markPracticed(q.id)}/>)}</div></section>:null}{!recent.length?<p className="py-10 text-center text-sm text-[#63709A]">这个筛选下暂时没有题目。</p>:null}</div>:null}
{tab==="cambridge"?<div className="space-y-4">{cambridgeBooks.map(b=><JournalPaper key={b.id} tone="paper" className="overflow-hidden"><button type="button" onClick={()=>setOpenBook(openBook===b.id?null:b.id)} className="flex w-full items-center justify-between gap-4 p-5 text-left"><div className="flex items-center gap-3"><BookMarked className="size-4 text-[var(--journal-blue)]"/><div><p className="text-sm font-medium text-[var(--journal-ink)]">{b.name}</p><p className="mt-0.5 text-[11px] text-[#63709A]">{b.year} · 已完成 {b.done} / 4 Test</p></div></div><span className="text-xs text-[#63709A]">{openBook===b.id?"收起":"展开"}</span></button>{openBook===b.id?<div className="border-t border-[var(--journal-line)] bg-[var(--journal-lavender)] px-5 py-4"><div className="grid gap-2 sm:grid-cols-2">{b.tests.map(t=><div key={t} className="border border-[var(--journal-line)] bg-[var(--journal-paper)] px-4 py-3"><p className="text-sm text-[var(--journal-ink)]">{t}</p><div className="mt-3 flex flex-wrap gap-1.5">{b.modules.map(m=><a key={m} href={moduleHref(m)} className="border border-[var(--journal-line)] bg-[var(--journal-paper)] px-2.5 py-1 text-[10px] text-[#63709A]">{m}</a>)}</div></div>)}</div><p className="mt-3 text-[10px] text-[#63709A]">当前按钮进入 Ivy 的结构化练习壳；题目内容待你导入合法拥有的 Cambridge 材料。</p></div>:null}</JournalPaper>)}</div>:null}
{tab==="official"?<div className="grid gap-4 md:grid-cols-2">{questions.filter(q=>q.sourceType==="official").map(q=>{const theme=themeByModule[q.module]??"subject-reading";const sub=subjectByModule[q.module]??"reading";return <div key={q.id} className={theme}><IndexCard subject={sub} className="p-5 pt-7"><div className="flex items-start justify-between"><FileText className="subject-text size-5"/><span className="subject-chip inline-flex items-center gap-1 px-2 py-0.5 text-[10px]"><ShieldCheck className="size-3"/>官方</span></div><p className="mt-6 text-sm font-medium text-[var(--journal-ink)]">{q.title}</p><p className="mt-1 text-[11px] text-[#63709A]">{q.module}</p><div className="mt-5 flex gap-2"><a href={officialHref(q.module)} className="border border-[var(--subject-color)] bg-[var(--journal-paper)] px-3 py-1.5 text-[11px] text-[var(--journal-ink)]">进入练习</a><Link to="/question" search={{id:q.id}} className="px-3 py-1.5 text-[11px] text-[#63709A]">详情</Link></div></IndexCard></div>})}</div>:null}
{tab==="personal"?<div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{personal.map(item=><Link key={item.title} to={item.to as "/library"} className="journal-folder p-5"><p className="text-sm font-medium text-[var(--journal-ink)]">{item.title}</p><p className="mt-1 text-[11px] text-[#63709A]">{item.hint}</p><p className="display mt-5 text-xl tabular-nums text-[var(--journal-ink)]">{item.count}</p></Link>)}</div><Button asChild variant="outline" className="rounded-sm border-[var(--journal-turquoise)]"><Link to="/library"><Plus className="mr-1 size-3.5"/>添加材料</Link></Button></div>:null}</div>}
