import { useEffect, useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Clock3, History, RotateCcw } from "lucide-react";
import { PageHeader, SectionTitle } from "@/components/ui-kit";
import { useAppState } from "@/state/app-state";
import { getExamHistory, type ExamSession } from "@/lib/exam-engine-store";

export const Route=createFileRoute("/history")({head:()=>({meta:[{title:"结果历史 · Ivy English"}]}),component:HistoryPage});

function moduleLabel(module:ExamSession["module"]){return module==="reading"?"阅读":module==="listening"?"听力":module==="writing"?"写作":"口语"}
function retry(module:ExamSession["module"]){if(module==="reading")return "/exam-v3?mode=familiarisation&scope=full";if(module==="listening")return "/listening-exam-v3?mode=familiarisation&scope=full";if(module==="writing")return "/writing-exam-v2?mode=familiarisation&scope=full";return "/speaking-workspace?mode=full"}
function formatDuration(seconds:number){const total=Math.max(0,Math.round(seconds));const minutes=Math.floor(total/60);const rest=total%60;return `${minutes}:${rest.toString().padStart(2,"0")}`}

function HistoryPage(){const {sessions}=useAppState();const [examHistory,setExamHistory]=useState<ExamSession[]>([]);useEffect(()=>setExamHistory(getExamHistory().filter(item=>item.status==="completed")),[]);const recent=useMemo(()=>sessions.slice(0,30),[sessions]);return <div className="space-y-9"><PageHeader title="结果历史" subtitle="完整保留 CBT、写作与口语练习记录；刷新页面后仍然可以回来复盘。"/>
<section><SectionTitle title="Exam Engine v4" subtitle={`${examHistory.length} 场`}/><div className="space-y-3">{examHistory.map(item=><article key={item.id} className="surface p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-[11px] text-muted-foreground"><span className="rounded-full bg-sage-soft px-2 py-0.5 text-sage-foreground">{moduleLabel(item.module)}</span><span>{item.mode==="full_exam"?"完整模拟":"专项练习"}</span></div><p className="mt-3 text-sm">{new Date(item.completedAt??item.startedAt).toLocaleString("zh-CN")}</p></div><div className="text-right"><p className="display text-xl tabular-nums">{typeof item.score==="number"?`${item.score} / ${item.answers.length}`:"Completed"}</p><p className="mt-1 inline-flex items-center gap-1 text-[11px] text-muted-foreground"><Clock3 className="size-3"/>{formatDuration(item.durationSeconds)}</p></div></div><div className="mt-4 flex flex-wrap gap-2 text-[11px] text-muted-foreground"><span>{item.answers.filter(answer=>answer.answer.trim()).length} answered</span>{item.annotations?.length?<span>· {item.annotations.length} annotations</span>:null}{item.vocabulary?.length?<span>· {item.vocabulary.length} vocabulary</span>:null}</div><a href={retry(item.module)} className="mt-4 inline-flex items-center gap-1.5 text-[11px] text-sage-foreground hover:underline"><RotateCcw className="size-3"/>再练一次</a></article>)}{!examHistory.length?<div className="surface py-12 text-center"><History className="mx-auto size-7 text-sage"/><p className="mt-4 text-sm">还没有完成的 Exam Engine 记录。</p><p className="mt-1 text-xs text-muted-foreground">完成一次 Reading / Listening / Writing 后会自动出现。</p></div>:null}</div></section>
<section><SectionTitle title="全部学习记录" subtitle={`${recent.length} 条最近记录`}/><div className="surface divide-y divide-border overflow-hidden">{recent.map(item=><Link key={item.id} to="/session" search={{id:item.id}} className="flex items-center justify-between gap-4 px-5 py-4 hover:bg-secondary/40"><div className="min-w-0"><p className="truncate text-sm">{item.activity}</p><p className="mt-1 text-[11px] text-muted-foreground">{item.date} · {item.module} · {item.durationMinutes} min</p></div><span className="shrink-0 text-xs tabular-nums">{item.score??""}</span></Link>)}</div></section></div>}
