import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Ear, FileText, Headphones, Mic, PenLine, BookOpenText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Callout, MiniBars, SectionTitle, StatusPill } from "@/components/ui-kit";
import { useAppState } from "@/state/app-state";
import { learningSignals, weekBreakdown } from "@/data/mock";
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Ivy English · 个人英语与 IELTS 学习空间"},{name:"description",content:"Ivy English 是一个安静的个人英语学习空间：今天学什么、听说读写练习、近期 IELTS 考场题回忆与长期进度，都在一处。"},{property:"og:title",content:"Ivy English · 个人英语学习空间"},{property:"og:description",content:"今天学什么、听说读写练习、近期题库与长期进度，一个安静的个人学习空间。"}]}),component:HomePage});
const quickStart=[{title:"听力",hint:"真实英语 · 听写 · Shadowing",icon:Headphones,module:"listening" as const},{title:"口语",hint:"自由表达 · IELTS Speaking",icon:Mic,module:"speaking" as const},{title:"阅读",hint:"文章阅读 · IELTS CBT",icon:BookOpenText,module:"reading" as const},{title:"写作",hint:"自由写作 · IELTS Writing",icon:PenLine,module:"writing" as const}];
function HomePage(){const {plan,isShortPlan,setShortPlan}=useAppState();const totalMinutes=plan.reduce((a,b)=>a+b.minutes,0);return <div className="space-y-14">
<header><h1 className="display text-3xl sm:text-4xl">晚上好，Ivy ♡</h1><p className="mt-2 text-sm text-muted-foreground">9月3日 · 英语基础阶段</p></header>
<section className="surface p-6 sm:p-8"><div className="flex items-baseline justify-between"><h2 className="text-xl">今天</h2><span className="text-xs text-muted-foreground">共 {totalMinutes} 分钟</span></div><div className="mt-6 divide-y divide-border">{plan.map(item=><div key={item.module} className="flex items-center justify-between gap-4 py-3.5"><div><p className="text-sm">{item.module}</p><p className="mt-0.5 text-xs text-muted-foreground">{item.hint}</p></div><span className="shrink-0 text-sm tabular-nums text-muted-foreground">{item.minutes} 分钟</span></div>)}</div><div className="mt-7 flex flex-wrap items-center gap-4"><Button asChild size="lg" className="rounded-full px-6"><Link to="/practice" search={{module:"listening"}}>开始今天的学习</Link></Button><button type="button" onClick={()=>setShortPlan(!isShortPlan)} className="text-xs text-muted-foreground underline decoration-border underline-offset-4 transition-colors hover:text-foreground">{isShortPlan?"恢复完整计划":"我今天只有 20 分钟"}</button></div></section>
<section><SectionTitle title="继续上次"/><div className="surface hover-lift flex flex-wrap items-center justify-between gap-4 p-5 sm:p-6"><div><p className="text-sm">IELTS Reading</p><p className="mt-1 text-xs text-muted-foreground">Cambridge 18 · Test 2 · Passage 3</p><p className="mt-3 text-xs text-muted-foreground"><span className="text-foreground tabular-nums">31 / 40</span><span className="mx-2 text-border">·</span>38 分钟</p></div><Button asChild variant="outline" className="rounded-full"><Link to="/practice" search={{module:"reading"}}>继续查看</Link></Button></div></section>
<section><SectionTitle title="开始学习"/><div className="grid grid-cols-2 gap-3 sm:gap-4 lg:grid-cols-4">{quickStart.map(c=><Link key={c.title} to="/practice" search={{module:c.module}} className="surface hover-lift flex flex-col gap-6 p-5"><c.icon className="size-5 text-sage" strokeWidth={1.6}/><div><p className="text-sm">{c.title}</p><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">{c.hint}</p></div></Link>)}</div></section>
<section><SectionTitle title="这周"/><div className="surface p-6 sm:p-8"><div className="flex flex-wrap items-end gap-x-10 gap-y-4"><div><p className="text-[11px] text-muted-foreground">总学习时间</p><p className="display mt-1 text-2xl">3小时42分钟</p></div><div><p className="text-[11px] text-muted-foreground">学习次数</p><p className="display mt-1 text-2xl">6 次</p></div></div><div className="mt-7"><MiniBars data={weekBreakdown.map(w=>({label:w.module,minutes:w.minutes}))}/></div></div></section>
<section><SectionTitle title="最近需要注意"/><div className="grid gap-3 md:grid-cols-3">{learningSignals.slice(0,3).map(s=><Link key={s.id} to="/progress" className="surface hover-lift flex flex-col gap-4 p-5"><p className="text-sm leading-relaxed">{s.title}</p><div className="mt-auto flex items-center justify-between"><span className="text-[11px] text-muted-foreground">{s.module}</span><StatusPill status={s.status}/></div></Link>)}</div></section>
<section><SectionTitle title="最近考场题" subtitle="近期考生回忆整理 · 非官方真题"/><div className="surface p-6 sm:p-8"><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-border bg-secondary/50 p-4"><div className="flex items-center gap-2 text-sm"><Mic className="size-4 text-sage" strokeWidth={1.6}/>Speaking</div><p className="mt-2 text-xs text-muted-foreground">Sep–Dec 2026 · 本季题库</p></div><div className="rounded-xl border border-border bg-secondary/50 p-4"><div className="flex items-center gap-2 text-sm"><FileText className="size-4 text-sage" strokeWidth={1.6}/>Writing</div><p className="mt-2 text-xs text-muted-foreground">近期考题</p></div></div><div className="mt-6"><Button asChild variant="outline" className="rounded-full"><Link to="/bank" search={{tab:"recent",subject:"口语"}}>查看近期题库<ArrowRight className="ml-1 size-3.5"/></Link></Button></div></div></section>
<Callout><span className="inline-flex items-center gap-2"><Ear className="size-3.5"/>现在以真实英语输入为主，IELTS 练习保持低频接触。</span></Callout></div>}