import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { BookOpenText, FileText, Link2, NotebookPen, Plus, Trash2, Upload, X } from "lucide-react";
import { PageHeader, SectionTitle, Chip } from "@/components/ui-kit";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { useAppState, type LibraryItemType } from "@/state/app-state";
import type { Module } from "@/data/mock";

export const Route=createFileRoute("/library")({head:()=>({meta:[{title:"资料库 · Ivy English"}]}),component:LibraryPage});
const types:{key:LibraryItemType;label:string;icon:typeof FileText}[]=[{key:"pdf",label:"PDF",icon:Upload},{key:"link",label:"网页链接",icon:Link2},{key:"question",label:"手动题目",icon:BookOpenText},{key:"note",label:"学习笔记",icon:NotebookPen}];
const modules:Module[]=["听力","口语","阅读","写作","词汇"];

function LibraryPage(){
  const {libraryItems,addLibraryItem,removeLibraryItem,mistakes,vocabulary}=useAppState();
  const [open,setOpen]=useState(false);const [type,setType]=useState<LibraryItemType>("pdf");const [title,setTitle]=useState("");const [url,setUrl]=useState("");const [notes,setNotes]=useState("");const [module,setModule]=useState<Module>("阅读");const [fileName,setFileName]=useState("");
  function save(){const finalTitle=title.trim()||fileName||"未命名材料";addLibraryItem({type,title:finalTitle,module,url:url.trim()||undefined,notes:[fileName&&type==="pdf"?`本地文件：${fileName}`:"",notes.trim()].filter(Boolean).join("\n")||undefined});setOpen(false);setTitle("");setUrl("");setNotes("");setFileName("");}
  return <div className="space-y-9"><PageHeader title="资料库" subtitle="题目、材料、错题和生词都留在 Ivy English 里；Notion 继续作为长期研究档案。"/>
    <div className="grid gap-3 sm:grid-cols-3"><Link to="/mistakes" className="surface hover-lift p-5"><p className="text-sm">错题本</p><p className="display mt-4 text-2xl">{mistakes.length}</p><p className="mt-1 text-[11px] text-muted-foreground">Reading / Listening 自动收集</p></Link><Link to="/vocabulary" className="surface hover-lift p-5"><p className="text-sm">生词本</p><p className="display mt-4 text-2xl">{vocabulary.length}</p><p className="mt-1 text-[11px] text-muted-foreground">来自真实学习语境</p></Link><div className="surface p-5"><p className="text-sm">我的材料</p><p className="display mt-4 text-2xl">{libraryItems.length}</p><p className="mt-1 text-[11px] text-muted-foreground">PDF · 链接 · 题目 · 笔记</p></div></div>
    <section><SectionTitle title="我的材料" action={<Button variant="outline" className="rounded-full" onClick={()=>setOpen(true)}><Plus className="mr-1 size-3.5"/>添加材料</Button>}/><div className="grid gap-3 md:grid-cols-2">{libraryItems.map(item=>{const meta=types.find(t=>t.key===item.type)!;const Icon=meta.icon;return <article key={item.id} className="surface p-5"><div className="flex items-start gap-3"><div className="flex size-9 shrink-0 items-center justify-center rounded-full bg-sage-soft text-sage-foreground"><Icon className="size-4"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm">{item.title}</p><p className="mt-1 text-[11px] text-muted-foreground">{meta.label}{item.module?` · ${item.module}`:""}</p></div><button type="button" onClick={()=>removeLibraryItem(item.id)} className="text-muted-foreground hover:text-foreground"><Trash2 className="size-3.5"/></button></div>{item.url?<a href={item.url} target="_blank" rel="noreferrer" className="mt-4 block truncate text-xs text-sage-foreground hover:underline">{item.url}</a>:null}{item.notes?<p className="mt-4 whitespace-pre-wrap rounded-lg bg-secondary/50 p-3 text-xs leading-5 text-muted-foreground">{item.notes}</p>:null}</article>})}{!libraryItems.length?<div className="surface col-span-full py-14 text-center"><p className="text-sm">资料库现在还是空的。</p><p className="mt-1 text-xs text-muted-foreground">可以先放一份 PDF、一个网页，或者一条自己整理的题目。</p></div>:null}</div></section>
    <div className="flex justify-end"><a href="https://www.notion.so" target="_blank" rel="noreferrer" className="text-xs text-muted-foreground underline underline-offset-4">打开 Notion 长期档案</a></div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-md rounded-2xl"><DialogHeader><DialogTitle className="display text-xl">添加材料</DialogTitle><DialogDescription className="text-xs">先把材料登记进 Ivy English；PDF 文件本体暂时仍保留在你的设备上。</DialogDescription></DialogHeader><div className="space-y-4"><div className="grid grid-cols-2 gap-2">{types.map(item=><button key={item.key} type="button" onClick={()=>setType(item.key)} className={`rounded-xl border px-3 py-3 text-left text-xs ${type===item.key?"border-sage bg-sage-soft/40":"border-border"}`}>{item.label}</button>)}</div>{type==="pdf"?<label className="flex cursor-pointer items-center justify-between rounded-xl border border-dashed border-border px-4 py-4 text-xs"><span>{fileName||"选择 PDF 文件"}</span><Upload className="size-4 text-sage"/><input type="file" accept="application/pdf" className="hidden" onChange={e=>setFileName(e.target.files?.[0]?.name??"")}/></label>:null}<Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="标题"/>{type==="link"?<Input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..."/>:null}<div className="flex flex-wrap gap-2">{modules.map(m=><Chip key={m} active={module===m} onClick={()=>setModule(m)}>{m}</Chip>)}</div><Textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3} className="resize-none" placeholder={type==="question"?"写下题目、答案或备注":"备注（可选）"}/><Button onClick={save} className="w-full">保存</Button></div></DialogContent></Dialog>
  </div>;
}
