import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { BookOpenText, FileText, History, Link2, NotebookPen, Plus, Trash2, Upload } from "lucide-react";
import { PageHeader, SectionTitle, Chip } from "@/components/ui-kit";
import { JournalPaper } from "@/components/journal-ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { useAppState, type LibraryItemType } from "@/state/app-state";
import type { Module } from "@/data/mock";
import { cn } from "@/lib/utils";

export const Route=createFileRoute("/library")({head:()=>({meta:[{title:"资料库 · Ivy English"}]}),component:LibraryPage});
const types:{key:LibraryItemType;label:string;icon:typeof FileText}[]=[{key:"pdf",label:"PDF",icon:Upload},{key:"link",label:"网页链接",icon:Link2},{key:"question",label:"手动题目",icon:BookOpenText},{key:"note",label:"学习笔记",icon:NotebookPen}];
const modules:Module[]=["听力","口语","阅读","写作","词汇"];
const materialTone:Record<LibraryItemType,string>={pdf:"bg-[var(--journal-yellow)]",link:"journal-grid bg-[var(--journal-paper)]",question:"bg-[var(--journal-peach)]",note:"journal-ledger bg-[var(--journal-paper)]"};
const materialTape:Record<LibraryItemType,string>={pdf:"bg-[var(--journal-peach)]",link:"bg-[var(--journal-yellow)]",question:"bg-[var(--journal-paper)]",note:"bg-[var(--journal-peach)]"};

function SummaryPaper({children,tone="paper",grid=false,lines=false}:{children:React.ReactNode;tone?:"paper"|"yellow"|"peach";grid?:boolean;lines?:boolean}){
  const tones={paper:"bg-[var(--journal-paper)]",yellow:"bg-[var(--journal-yellow)]",peach:"bg-[var(--journal-peach)]"};
  return <div className={cn("relative min-h-40 overflow-hidden border border-[var(--journal-line)] p-5 shadow-[4px_5px_0_rgba(23,48,109,.07)]",tones[tone],grid&&"journal-grid",lines&&"journal-ledger")}><span className="absolute -top-px left-5 h-3 w-20 border-x border-b border-[var(--journal-line)] bg-[var(--journal-paper)]"/>{children}</div>;
}

function LibraryPage(){const {libraryItems,addLibraryItem,removeLibraryItem,mistakes,vocabulary,sessions}=useAppState();const [open,setOpen]=useState(false);const [type,setType]=useState<LibraryItemType>("pdf");const [title,setTitle]=useState("");const [url,setUrl]=useState("");const [notes,setNotes]=useState("");const [module,setModule]=useState<Module>("阅读");const [fileName,setFileName]=useState("");function save(){const finalTitle=title.trim()||fileName||"未命名材料";const finalUrl=url.trim();const finalNotes=[fileName&&type==="pdf"?`本地文件：${fileName}`:"",notes.trim()].filter(Boolean).join("\n");addLibraryItem({type,title:finalTitle,module,...(finalUrl?{url:finalUrl}:{}),...(finalNotes?{notes:finalNotes}:{})});setOpen(false);setTitle("");setUrl("");setNotes("");setFileName("");}
return <div className="journal-page space-y-9"><PageHeader title="资料库" subtitle="材料、错题、生词和完整学习历史都集中在这里；进度页只负责分析变化。"/>
<div className="grid grid-cols-2 gap-3 lg:grid-cols-4 lg:gap-4">
<Link to="/mistakes" className="block"><SummaryPaper tone="yellow"><p className="text-sm font-medium text-[var(--journal-ink)]">错题本</p><p className="display mt-5 text-3xl text-[var(--journal-ink)]">{mistakes.length}</p><p className="mt-2 text-[11px] leading-5 text-[#63709A]">Reading / Listening 自动收集</p><span className="absolute bottom-3 right-3 rotate-[-3deg] border border-[var(--journal-ink)] px-2 py-0.5 text-[9px] text-[var(--journal-ink)]">REVIEW</span></SummaryPaper></Link>
<Link to="/vocabulary" className="block"><SummaryPaper tone="paper" grid><p className="text-sm font-medium text-[var(--journal-ink)]">生词本</p><p className="display mt-5 text-3xl text-[var(--journal-ink)]">{vocabulary.length}</p><p className="mt-2 text-[11px] leading-5 text-[#63709A]">来自真实学习语境</p><span className="absolute -right-1 top-9 h-8 w-5 border-y border-l border-[var(--journal-line)] bg-[var(--journal-peach)]"/></SummaryPaper></Link>
<Link to="/history" search={{module:"all"}} className="block"><SummaryPaper tone="peach" lines><div className="flex items-center justify-between"><p className="text-sm font-medium text-[var(--journal-ink)]">学习历史</p><History className="size-4 text-[var(--journal-ink)]"/></div><p className="display mt-5 text-3xl text-[var(--journal-ink)]">{sessions.length}</p><p className="mt-2 text-[11px] leading-5 text-[#63709A]">题目 · 回答 · 作文 · 录音</p></SummaryPaper></Link>
<SummaryPaper tone="paper"><p className="text-sm font-medium text-[var(--journal-ink)]">我的材料</p><p className="display mt-5 text-3xl text-[var(--journal-ink)]">{libraryItems.length}</p><p className="mt-2 text-[11px] leading-5 text-[#63709A]">PDF · 链接 · 题目 · 笔记</p><span className="absolute bottom-3 right-3 h-7 w-16 rotate-2 bg-[var(--journal-yellow)] opacity-80"/></SummaryPaper>
</div>
<section><SectionTitle title="我的材料" action={<Button variant="outline" className="rounded-sm border-[var(--journal-ink)] bg-[var(--journal-paper)] text-[var(--journal-ink)]" onClick={()=>setOpen(true)}><Plus className="mr-1 size-3.5"/>添加材料</Button>}/><div className="grid gap-4 md:grid-cols-2">{libraryItems.map((item,index)=>{const meta=types.find(t=>t.key===item.type)!;const Icon=meta.icon;return <article key={item.id} className={cn("relative overflow-visible border border-[var(--journal-line)] p-5 shadow-[4px_5px_0_rgba(23,48,109,.07)]",materialTone[item.type],index%2===0?"md:-rotate-[0.15deg]":"md:rotate-[0.15deg]")}><span className={cn("absolute -top-2 left-1/2 h-4 w-14 -translate-x-1/2 rotate-[-1deg] border-x border-[rgba(23,48,109,.10)] opacity-90",materialTape[item.type])}/><div className="flex items-start gap-3"><Icon className="size-5 shrink-0 text-[var(--journal-ink)]" strokeWidth={1.7}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-[var(--journal-ink)]">{item.title}</p><p className="mt-1 text-[11px] text-[#63709A]">{meta.label}{item.module?` · ${item.module}`:""}</p></div><button type="button" onClick={()=>removeLibraryItem(item.id)} className="text-[#63709A] hover:text-[var(--journal-danger)]"><Trash2 className="size-3.5"/></button></div>{item.url?<a href={item.url} target="_blank" rel="noreferrer" className="journal-link mt-4 block truncate text-xs">{item.url}</a>:null}{item.notes?<p className="mt-4 whitespace-pre-wrap border-t border-[color:var(--journal-line)] pt-3 text-xs leading-6 text-[#52608C]">{item.notes}</p>:null}<span className="absolute -right-px bottom-4 h-7 w-3 border-y border-l border-[var(--journal-line)] bg-[var(--journal-paper)]"/></article>})}{!libraryItems.length?<JournalPaper tone="yellow" className="col-span-full py-14 text-center"><span className="absolute left-1/2 top-0 h-4 w-16 -translate-x-1/2 -translate-y-1/2 rotate-[-1deg] bg-[var(--journal-peach)]"/><p className="text-sm text-[var(--journal-ink)]">资料库现在还是空的。</p><p className="mt-1 text-xs text-[#63709A]">可以先放一份 PDF、一个网页，或者一条自己整理的题目。</p></JournalPaper>:null}</div></section>
<div className="flex justify-end"><a href="https://www.notion.so" target="_blank" rel="noreferrer" className="journal-link text-xs underline underline-offset-4">打开 Notion 长期档案</a></div>
<Dialog open={open} onOpenChange={setOpen}><DialogContent className="journal-app max-w-md rounded-sm border-[var(--journal-line)] bg-[var(--journal-canvas)]"><DialogHeader><DialogTitle className="display text-xl text-[var(--journal-ink)]">添加材料</DialogTitle><DialogDescription className="text-xs text-[#63709A]">先把材料登记进 Ivy English；PDF 文件本体暂时仍保留在你的设备上。</DialogDescription></DialogHeader><div className="space-y-4"><div className="grid grid-cols-2 gap-2">{types.map((item,index)=><button key={item.key} type="button" onClick={()=>setType(item.key)} className={cn("border px-3 py-3 text-left text-xs",type===item.key?"border-[var(--journal-ink)] text-[var(--journal-ink)]":"border-[var(--journal-line)] bg-[var(--journal-paper)]",type===item.key&&["bg-[var(--journal-yellow)]","bg-[var(--journal-paper)]","bg-[var(--journal-peach)]","journal-ledger bg-[var(--journal-paper)]"][index])}>{item.label}</button>)}</div>{type==="pdf"?<label className="flex cursor-pointer items-center justify-between border border-dashed border-[var(--journal-ink)] bg-[var(--journal-paper)] px-4 py-4 text-xs"><span>{fileName||"选择 PDF 文件"}</span><Upload className="size-4 text-[var(--journal-ink)]"/><input type="file" accept="application/pdf" className="hidden" onChange={e=>setFileName(e.target.files?.[0]?.name??"")}/></label>:null}<Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="标题"/>{type==="link"?<Input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..."/>:null}<div className="flex flex-wrap gap-2">{modules.map(m=><Chip key={m} active={module===m} onClick={()=>setModule(m)}>{m}</Chip>)}</div><Textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3} className="resize-none" placeholder={type==="question"?"写下题目、答案或备注":"备注（可选）"}/><Button onClick={save} className="journal-button w-full rounded-sm">保存</Button></div></DialogContent></Dialog></div>}
