import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowUpRight, AudioLines,BookMarked,BookOpenText,ClipboardList,FileText,FolderOpen,Headphones,History,Image,Layers,Link2,ListMusic,Mic,NotebookPen,PenLine,Repeat,Timer,TrendingUp,Video } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Callout, PageHeader, SectionTitle } from "@/components/ui-kit";
import { IndexCard, JournalPaper, ReceiptCard } from "@/components/journal-ui";
import { PracticeTimerPopover } from "@/components/PracticeTimerPopover";
import { useAppState } from "@/state/app-state";
import { moduleMeta, type LearningModuleKey } from "@/lib/learning-navigation";
import { cn } from "@/lib/utils";

type ModuleKey=LearningModuleKey;
type Subject="listening"|"speaking"|"reading"|"writing";
export const Route=createFileRoute("/practice")({validateSearch:(search:Record<string,unknown>):{module:ModuleKey}=>{const valid:ModuleKey[]=["listening","speaking","reading","writing"];return{module:valid.includes(search.module as ModuleKey)?search.module as ModuleKey:"listening"}},head:()=>({meta:[{title:"学习 · Ivy English"},{name:"description",content:"听力、口语、阅读、写作四项练习入口。"}]}),component:PracticePage});
const tabs:{key:ModuleKey;label:string;icon:LucideIcon}[]=[{key:"listening",label:"听力",icon:Headphones},{key:"speaking",label:"口语",icon:Mic},{key:"reading",label:"阅读",icon:BookOpenText},{key:"writing",label:"写作",icon:PenLine}];
const subjects:Record<ModuleKey,Subject>={listening:"listening",speaking:"speaking",reading:"reading",writing:"writing"};
const subjectClass:Record<ModuleKey,string>={listening:"subject-listening journal-subject-listening",speaking:"subject-speaking journal-subject-speaking",reading:"subject-reading journal-subject-reading",writing:"subject-writing journal-subject-writing"};
interface Item{title:string;hint?:string;icon:LucideIcon;badge?:string;to?:{tab:"recent";subject:string};href?:string}
function ItemCard({item,subject}:{item:Item;subject:Subject}){const inner=<><div className="flex items-start justify-between gap-3"><item.icon className="subject-text size-5" strokeWidth={1.6}/>{item.badge?<span className="subject-chip rounded-sm px-2 py-0.5 text-[9px] font-semibold tracking-[0.08em]">{item.badge}</span>:null}</div><div className="mt-7"><p className="text-sm font-medium text-[var(--journal-ink)]">{item.title}</p>{item.hint?<p className="mt-1 text-[11px] leading-relaxed text-[#63709A]">{item.hint}</p>:null}</div></>;const body=(content:React.ReactNode)=> <IndexCard subject={subject} className="h-full min-h-36 p-5 pt-7 transition-transform duration-150 hover:-translate-y-0.5">{content}</IndexCard>;if(item.href)return <a href={item.href} className="block h-full">{body(inner)}</a>;return item.to?<Link to="/bank" search={item.to} className="block h-full">{body(inner)}</Link>:body(inner)}
function Group({title,items,subject}:{title:string;items:Item[];subject:Subject}){return <section><SectionTitle title={title}/><div className="grid grid-cols-2 gap-3 sm:gap-4 lg:grid-cols-4">{items.map(i=><ItemCard key={i.title} item={i} subject={subject}/>)}</div></section>}

function PracticePage(){const {module}=Route.useSearch();const navigate=useNavigate({from:Route.fullPath});const {sessions}=useAppState();const meta=moduleMeta(module);const recent=sessions.find(s=>s.module===meta.label);const subject=subjects[module];
return <div className={cn("journal-page space-y-10",subjectClass[module])}><PageHeader title="学习" subtitle="今天想练什么？学习负责开始练习；进度和历史各自有清楚的去处。"/>
<div className="grid grid-cols-2 gap-3 sm:grid-cols-4 sm:gap-4">{tabs.map(t=>{const active=module===t.key;return <button key={t.key} type="button" onClick={()=>navigate({search:{module:t.key}})} className={cn(subjectClass[t.key],"flex min-h-28 flex-col items-start justify-between border bg-[var(--journal-paper)] p-4 text-left shadow-[3px_4px_0_rgba(63,99,242,.06)] transition-all sm:min-h-32 sm:p-5",active?"subject-border bg-[var(--subject-soft)]":"border-[var(--journal-line)] hover:border-[var(--subject-color)]")}><t.icon className="subject-text size-5" strokeWidth={1.7}/><span className={cn("text-sm font-medium",active?"subject-text":"text-[var(--journal-ink)]")}>{t.label}</span></button>})}</div>

<section className="journal-index-card relative border-[var(--subject-color)] p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-medium text-[var(--journal-ink)]">{meta.label}工作台</p><p className="mt-1 text-[11px] text-[#63709A]">学习、历史、进度与模拟考试从这里分流。</p></div><div className="flex flex-wrap gap-2"><Link to="/history" search={{module}} className="inline-flex items-center gap-1.5 border border-[var(--subject-color)] bg-[var(--journal-paper)] px-3.5 py-2 text-xs text-[var(--journal-ink)]"><History className="subject-text size-3.5"/>历史</Link><Link to="/progress-detail" search={{module}} className="inline-flex items-center gap-1.5 border border-[var(--subject-color)] bg-[var(--journal-paper)] px-3.5 py-2 text-xs text-[var(--journal-ink)]"><TrendingUp className="subject-text size-3.5"/>进度</Link><a href={meta.examHref} className="subject-button inline-flex items-center gap-1.5 px-3.5 py-2 text-xs"><ArrowUpRight className="size-3.5"/>{meta.examLabel}</a></div></div></section>

<ReceiptCard className="p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><Timer className="size-5 text-[var(--journal-turquoise)]" strokeWidth={1.6}/><div><p className="text-sm font-medium text-[var(--journal-ink)]">沉浸专注</p><p className="mt-0.5 max-w-xl text-[11px] leading-5 text-[#63709A]">把它当作全局学习计时器：可以不计时、正向记录实际用时，或选择 20 / 30 / 40 / 60 分钟倒计时，也可以输入自定义时长。停止后可以继续，重置不会影响学习记录。</p></div></div><PracticeTimerPopover defaultMinutes={20} storageKey={`ivy-focus-timer-${module}`}/></div></ReceiptCard>

{module==="listening"?<div className="space-y-10"><Group title="日常英语" subject="listening" items={[{title:"真实视频听力",hint:"YouTube / B站 / 访谈",icon:Video,href:"/study-workspace?mode=video"},{title:"盲听与听写",hint:"明显播放器 · 听写 · 对照",icon:AudioLines,href:"/study-workspace?mode=dictation"},{title:"Shadowing",hint:"播放控制 · 跟读 · 复盘",icon:Repeat,href:"/study-workspace?mode=shadowing"},{title:"分级听力",hint:"短素材 · 低压力",icon:ListMusic,href:"/study-workspace?mode=graded"}]}/><Group title="IELTS Listening" subject="listening" items={[{title:"Section 练习",hint:"可拖进度 / 暂停 / 跳转 / 重放",icon:Layers,badge:"CBT",href:"/listening-exam-v3?mode=familiarisation&scope=section"},{title:"完整模拟",hint:"4 Sections · 40 题 · 计时方式可选",icon:Timer,badge:"CBT",href:"/listening-exam-v3?mode=familiarisation&scope=full"},{title:"听力历史",hint:"材料、回答、成绩与复盘",icon:History,href:"/history?module=listening"},{title:"听力进度",hint:"投入、成绩和薄弱项",icon:TrendingUp,href:"/progress-detail?module=listening"}]}/><Callout>现在以真实英语输入为主，IELTS 练习保持低频接触。</Callout></div>:null}
{module==="speaking"?<div className="space-y-10"><Group title="日常口语" subject="speaking" items={[{title:"自由表达",hint:"不限时录音",icon:Mic,href:"/speaking-workspace?mode=free"},{title:"一分钟话题",hint:"换题 / 自己出题 / 60 秒",icon:Timer,href:"/speaking-workspace?mode=minute"},{title:"复述练习",hint:"换文本 / 自己粘贴",icon:Repeat,href:"/speaking-workspace?mode=retell"},{title:"图片描述",hint:"换图片 / 上传图片",icon:Image,href:"/speaking-workspace?mode=image"},{title:"今日话题",hint:"随机换题 / 自己出题",icon:NotebookPen,href:"/speaking-workspace?mode=today"}]}/><Group title="IELTS Speaking" subject="speaking" items={[{title:"Part 1",hint:"题目进度 · 自由选题 · 换题",icon:Mic,href:"/speaking-workspace?mode=part1"},{title:"Part 2",hint:"1 分钟准备 · 2 分钟回答",icon:ClipboardList,href:"/speaking-workspace?mode=part2"},{title:"Part 3",hint:"多题切换 · 深入讨论",icon:Layers,href:"/speaking-workspace?mode=part3"},{title:"完整模拟",hint:"Part 1–3 连续",icon:Timer,href:"/speaking-workspace?mode=full"},{title:"当季口语题库",hint:"Sep–Dec 2026 · 考生回忆整理",icon:BookMarked,badge:"近期",to:{tab:"recent",subject:"口语"}},{title:"口语历史",hint:"题目、时长和录音",icon:History,href:"/history?module=speaking"}]}/></div>:null}
{module==="reading"?<div className="space-y-10"><Group title="日常阅读" subject="reading" items={[{title:"文章阅读",hint:"新闻 · 长文",icon:BookOpenText,href:"/study-workspace?mode=article"},{title:"学术文章",hint:"偏 IELTS 语域",icon:FileText,href:"/study-workspace?mode=academic"},{title:"保存的网页",hint:"稍后读",icon:Link2,href:"/study-workspace?mode=saved"},{title:"我的材料",hint:"PDF · 老师的材料",icon:FolderOpen,href:"/study-workspace?mode=material"}]}/><Group title="IELTS Reading" subject="reading" items={[{title:"Cambridge / 官方",hint:"单 Passage · 默认 20 分钟 · 计时可选",icon:BookMarked,badge:"CBT",href:"/exam-v3?mode=familiarisation&scope=passage"},{title:"近期题型",hint:"考生回忆整理",icon:ClipboardList,to:{tab:"recent",subject:"阅读"}},{title:"我的题库",hint:"错题 · 收藏",icon:FolderOpen,href:"/mistakes"},{title:"完整 CBT",hint:"3 Passages · 40 题 · 计时方式可选",icon:Timer,badge:"CBT",href:"/exam-v3?mode=familiarisation&scope=full"},{title:"阅读历史",hint:"材料、笔记、答案和标注",icon:History,href:"/history?module=reading"}]}/>{recent?<section><SectionTitle title="最近一次"/><JournalPaper tone="paper" className="p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-medium text-[var(--journal-ink)]">{recent.activity}</p><p className="mt-1 text-xs text-[#63709A]">{recent.date}</p><p className="mt-3 text-sm tabular-nums text-[var(--subject-reading)]">{recent.score??`${recent.durationMinutes} min`}</p></div><Button asChild variant="outline" className="rounded-sm border-[var(--subject-reading)]"><Link to="/session" search={{id:recent.id,from:"practice",module}}>查看完整记录</Link></Button></div></JournalPaper></section>:null}</div>:null}
{module==="writing"?<div className="space-y-10"><Group title="日常写作" subject="writing" items={[{title:"自由写作",hint:"不限题目",icon:PenLine,href:"/study-workspace?mode=free-writing"},{title:"日记",hint:"每天几句话",icon:NotebookPen,href:"/study-workspace?mode=journal"},{title:"观点表达",hint:"一段话讲清立场",icon:FileText,href:"/study-workspace?mode=opinion"}]}/><Group title="IELTS Writing" subject="writing" items={[{title:"Task 1",hint:"只练 Task 1 · 默认 20 分钟",icon:FileText,badge:"CBT",href:"/writing-exam-v2?mode=familiarisation&scope=task1"},{title:"Task 2",hint:"只练 Task 2 · 默认 40 分钟",icon:PenLine,badge:"CBT",href:"/writing-exam-v2?mode=familiarisation&scope=task2"},{title:"近期考题",hint:"考生回忆整理",icon:ClipboardList,to:{tab:"recent",subject:"写作"}},{title:"完整模拟",hint:"Task 1 + Task 2 · 默认 60 分钟 · 计时可选",icon:Timer,badge:"CBT",href:"/writing-exam-v2?mode=familiarisation&scope=full"},{title:"历史作文",hint:"完整查看题目与正文",icon:History,href:"/history?module=writing"}]}/>{recent?<section><SectionTitle title="最近一篇"/><JournalPaper tone="paper" className="p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-medium text-[var(--journal-ink)]">{recent.activity}</p><p className="mt-1 text-xs text-[#63709A]">{recent.date}</p><p className="mt-3 text-sm tabular-nums text-[var(--subject-writing)]">{recent.score??`${recent.durationMinutes} min`}</p></div><Button asChild variant="outline" className="rounded-sm border-[var(--subject-writing)]"><Link to="/session" search={{id:recent.id,from:"practice",module}}>查看完整作文</Link></Button></div></JournalPaper></section>:null}</div>:null}</div>}
