import { useEffect, useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, BarChart3, BookOpenText, ChevronRight, Clock3, Headphones, Mic, PenLine, Target, TrendingUp } from "lucide-react";
import { PageHeader, SectionTitle, TrendChart } from "@/components/ui-kit";
import { IndexCard, JournalPaper, ReceiptCard } from "@/components/journal-ui";
import { useAppState } from "@/state/app-state";
import { listRecordings } from "@/lib/media-store";
import { labelFromKey, moduleMeta, type LearningModuleKey } from "@/lib/learning-navigation";
import type { StudySession } from "@/data/mock";

export const Route=createFileRoute("/progress-detail")({validateSearch:(search:Record<string,unknown>):{module:LearningModuleKey}=>{const valid:LearningModuleKey[]=["listening","speaking","reading","writing"];return{module:valid.includes(search.module as LearningModuleKey)?search.module as LearningModuleKey:"listening"}},head:()=>({meta:[{title:"分项进度 · Ivy English"}]}),component:ProgressDetailPage});
const icons={listening:Headphones,speaking:Mic,reading:BookOpenText,writing:PenLine};
const subjects={listening:"listening",speaking:"speaking",reading:"reading",writing:"writing"} as const;
function formatMinutes(total:number){const h=Math.floor(total/60);const m=total%60;return h?`${h}h ${m.toString().padStart(2,"0")}m`:`${m}m`}
function scoreValue(value?:string){const m=value?.match(/(\d+)\s*\/\s*(\d+)/);return m?{value:Number(m[1]),total:Number(m[2])}:null}
function wordValue(value?:string){const m=value?.match(/(\d+)\s*words?/i);return m?Number(m[1]):null}
function isIelts(session:StudySession){return /IELTS|CBT|Task\s*[12]|Speaking Part/i.test(`${session.activity} ${session.tool??""}`)}
function bars(items:[string,number][],empty:string){const max=Math.max(...items.map(([,count])=>count),1);return items.length?<div className="space-y-3">{items.map(([label,count])=><div key={label}><div className="flex items-center justify-between gap-3 text-xs"><span className="truncate text-[var(--journal-ink)]">{label}</span><span className="shrink-0 tabular-nums text-[#63709A]">{count}</span></div><div className="mt-1.5 h-2 overflow-hidden bg-[#EEF4FF]"><div className="h-full bg-[var(--page-subject,var(--journal-turquoise))]" style={{width:`${Math.max(8,count/max*100)}%`}}/></div></div>)}</div>:<p className="py-5 text-xs text-[#63709A]">{empty}</p>}

function ProgressDetailPage(){const {module}=Route.useSearch();const meta=moduleMeta(module);const label=labelFromKey(module);const Icon=icons[module];const subject=subjects[module];const {sessions,mistakes,vocabulary,signals}=useAppState();const scoped=useMemo(()=>sessions.filter(s=>s.module===label),[label,sessions]);const [recordingCount,setRecordingCount]=useState(0);useEffect(()=>{if(module!=="speaking")return;void listRecordings().then(items=>setRecordingCount(items.length)).catch(()=>setRecordingCount(0))},[module]);const totalMinutes=scoped.reduce((sum,s)=>sum+s.durationMinutes,0);const daily=scoped.filter(s=>!isIelts(s));const ielts=scoped.filter(isIelts);const grouped=new Map<string,number>();[...scoped].reverse().forEach(s=>grouped.set(s.date,(grouped.get(s.date)??0)+s.durationMinutes));const trend=Array.from(grouped.entries()).slice(-12).map(([date,minutes])=>({label:date.slice(5),minutes}));const scoreRows=scoped.map(s=>({session:s,score:scoreValue(s.score)})).filter((row):row is {session:StudySession;score:{value:number;total:number}}=>Boolean(row.score));const wordRows=scoped.map(s=>({session:s,words:wordValue(s.score)})).filter((row):row is {session:StudySession;words:number}=>typeof row.words==="number");const avgScore=scoreRows.length?scoreRows.slice(0,5).reduce((sum,row)=>sum+row.score.value,0)/Math.min(5,scoreRows.length):null;const totalWords=wordRows.reduce((sum,row)=>sum+row.words,0);const avgWords=wordRows.length?Math.round(wordRows.slice(0,8).reduce((sum,row)=>sum+row.words,0)/Math.min(8,wordRows.length)):null;const writingWpm=wordRows.length?wordRows.reduce((sum,row)=>sum+row.words/Math.max(1,row.session.durationMinutes),0)/wordRows.length:null;const moduleMistakes=mistakes.filter(m=>m.module===label);const moduleVocabulary=vocabulary.filter(v=>v.module===label);const moduleSignals=signals.filter(s=>s.module===label);const activityCounts=Object.entries(scoped.reduce<Record<string,number>>((acc,s)=>{acc[s.activity]=(acc[s.activity]??0)+1;return acc},{})).sort((a,b)=>b[1]-a[1]).slice(0,6) as [string,number][];const mistakeCounts=Object.entries(moduleMistakes.reduce<Record<string,number>>((acc,m)=>{const key=m.kind||"其他";acc[key]=(acc[key]??0)+1;return acc},{})).sort((a,b)=>b[1]-a[1]).slice(0,6) as [string,number][];const primaryStat=module==="writing"?`${totalWords} words`:module==="speaking"?`${recordingCount} 录音`:scoreRows[0]?`${scoreRows[0].score.value} / ${scoreRows[0].score.total}`:`${scoped.length} 次`;const theme=`subject-${module} journal-subject-${module}`;
return <div className={`${theme} journal-page space-y-9`}><Link to="/progress" className="journal-link inline-flex items-center gap-1.5 text-xs"><ArrowLeft className="size-3.5"/>返回进度总览</Link><PageHeader title={`${label}进度`} subtitle={`${meta.english} 的学习投入、历史表现、练习分布和薄弱项都集中在这里。`} action={<Icon className="journal-subject-accent size-7" strokeWidth={1.7}/>}/>
<ReceiptCard className="grid gap-3 p-5 sm:grid-cols-2 sm:p-6 lg:grid-cols-4"><div className="journal-stat"><Clock3 className="journal-subject-accent size-4"/><p className="mt-4 text-[11px] text-[#63709A]">累计学习</p><p className="display mt-1 text-2xl text-[var(--journal-ink)]">{formatMinutes(totalMinutes)}</p></div><div className="journal-stat"><BarChart3 className="journal-subject-accent size-4"/><p className="mt-4 text-[11px] text-[#63709A]">学习记录</p><p className="display mt-1 text-2xl text-[var(--journal-ink)]">{scoped.length}</p></div><div className="journal-stat"><Target className="journal-subject-accent size-4"/><p className="mt-4 text-[11px] text-[#63709A]">最近表现</p><p className="display mt-1 text-2xl text-[var(--journal-ink)]">{primaryStat}</p></div><div className="journal-stat"><TrendingUp className="journal-subject-accent size-4"/><p className="mt-4 text-[11px] text-[#63709A]">Daily / IELTS</p><p className="display mt-1 text-xl text-[var(--journal-ink)]">{daily.length} / {ielts.length}</p></div></ReceiptCard>
<JournalPaper tone="paper" className="p-6"><SectionTitle title="学习时间趋势" subtitle="只读取真实保存的学习记录"/>{trend.length?<TrendChart data={trend}/>:<p className="py-10 text-center text-xs text-[#63709A]">还没有足够记录生成趋势。</p>}</JournalPaper>
{module==="listening"||module==="reading"?<section><SectionTitle title="IELTS 表现"/><div className="grid gap-3 lg:grid-cols-[0.8fr_1.2fr]"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1"><IndexCard subject={subject} className="p-5 pt-7"><p className="text-sm font-medium text-[var(--journal-ink)]">最近原始得分</p><p className="display subject-text mt-3 text-2xl">{scoreRows[0]?`${scoreRows[0].score.value} / ${scoreRows[0].score.total}`:"暂无"}</p></IndexCard><IndexCard subject={subject} className="p-5 pt-7"><p className="text-sm font-medium text-[var(--journal-ink)]">近 5 次平均</p><p className="display subject-text mt-3 text-2xl">{avgScore===null?"暂无":`${avgScore.toFixed(1)} / ${scoreRows[0]?.score.total??40}`}</p></IndexCard></div><JournalPaper tone="paper" className="overflow-hidden"><div className="divide-y divide-[color:var(--journal-line)]">{scoreRows.slice(0,6).map(row=><Link key={row.session.id} to="/session" search={{id:row.session.id,from:"progress",module}} className="journal-list-row flex items-center justify-between gap-4 px-5 py-3.5"><div><p className="text-sm font-medium text-[var(--journal-ink)]">{row.session.activity}</p><p className="mt-1 text-[11px] text-[#63709A]">{row.session.date} · {row.session.durationMinutes} min</p></div><span className="display journal-subject-accent text-lg tabular-nums">{row.score.value} / {row.score.total}</span></Link>)}{!scoreRows.length?<p className="p-6 text-xs text-[#63709A]">还没有 IELTS 原始得分记录。</p>:null}</div></JournalPaper></div></section>:null}
{module==="writing"?<section><SectionTitle title="写作数据"/><div className="grid gap-3 md:grid-cols-4"><IndexCard subject="writing" className="p-5 pt-7"><p className="text-xs text-[#63709A]">累计字数</p><p className="display mt-2 text-2xl text-[var(--journal-ink)]">{totalWords}</p></IndexCard><IndexCard subject="writing" className="p-5 pt-7"><p className="text-xs text-[#63709A]">近 8 篇平均</p><p className="display mt-2 text-2xl text-[var(--journal-ink)]">{avgWords??"—"}</p></IndexCard><IndexCard subject="writing" className="p-5 pt-7"><p className="text-xs text-[#63709A]">平均速度</p><p className="display mt-2 text-2xl text-[var(--journal-ink)]">{writingWpm===null?"—":`${writingWpm.toFixed(1)}`}</p><p className="mt-1 text-[10px] text-[#63709A]">words / min</p></IndexCard><IndexCard subject="writing" className="p-5 pt-7"><p className="text-xs text-[#63709A]">有字数记录</p><p className="display mt-2 text-2xl text-[var(--journal-ink)]">{wordRows.length}</p></IndexCard></div></section>:null}
{module==="speaking"?<section><SectionTitle title="口语练习"/><div className="grid gap-3 md:grid-cols-3"><Link to="/recordings"><IndexCard subject="speaking" className="h-full p-5 pt-7"><p className="text-xs text-[#63709A]">历史录音</p><p className="display mt-2 text-2xl text-[var(--journal-ink)]">{recordingCount}</p><p className="subject-text mt-2 text-[11px]">进入录音历史</p></IndexCard></Link><IndexCard subject="speaking" className="p-5 pt-7"><p className="text-xs text-[#63709A]">开口记录</p><p className="display mt-2 text-2xl text-[var(--journal-ink)]">{scoped.length}</p></IndexCard><IndexCard subject="speaking" className="p-5 pt-7"><p className="text-xs text-[#63709A]">累计时长</p><p className="display mt-2 text-2xl text-[var(--journal-ink)]">{formatMinutes(totalMinutes)}</p></IndexCard></div></section>:null}
<section className="grid gap-5 lg:grid-cols-2"><div><SectionTitle title="练习分布"/><JournalPaper tone="paper" className="p-5">{bars(activityCounts,"还没有练习记录。")}</JournalPaper></div><div><SectionTitle title={module==="listening"||module==="reading"?"错题类型":"复盘与积累"}/><JournalPaper tone="yellow" className="p-5">{module==="listening"||module==="reading"?bars(mistakeCounts,"暂时没有自动收集的错题。"):<div className="space-y-3 text-sm text-[var(--journal-ink)]"><div className="flex justify-between"><span>错题 / 待复盘</span><span>{moduleMistakes.length}</span></div><div className="flex justify-between"><span>相关生词</span><span>{moduleVocabulary.length}</span></div><div className="flex justify-between"><span>学习问题</span><span>{moduleSignals.length}</span></div>{moduleSignals.slice(0,3).map(signal=><p key={signal.id} className="journal-ledger border border-[color:var(--journal-line)] bg-[var(--journal-paper)] p-3 text-xs leading-6 text-[#52608C]">{signal.title}</p>)}</div>}</JournalPaper></div></section>
{(module==="listening"||module==="reading")&&moduleSignals.length?<section><SectionTitle title="正在关注的问题"/><div className="grid gap-3 md:grid-cols-2">{moduleSignals.slice(0,4).map(signal=><JournalPaper key={signal.id} tone="yellow" className="p-5"><p className="text-sm font-medium text-[var(--journal-ink)]">{signal.title}</p><p className="mt-2 text-xs leading-5 text-[#63709A]">{signal.evidence}</p><p className="mt-4 border-l-2 border-[var(--page-subject)] bg-[var(--journal-paper)] p-3 text-xs leading-5 text-[var(--journal-ink)]">下一步：{signal.nextAction}</p></JournalPaper>)}</div></section>:null}
<section><SectionTitle title="最近的学习" action={<Link to="/history" search={{module}} className="subject-text text-xs font-semibold">查看全部历史</Link>}/><JournalPaper tone="paper" className="overflow-hidden"><div className="divide-y divide-[color:var(--journal-line)]">{scoped.slice(0,10).map(s=><Link key={s.id} to="/session" search={{id:s.id,from:"progress",module}} className="journal-list-row flex items-center gap-4 px-5 py-4"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-[var(--journal-ink)]">{s.activity}</p><p className="mt-1 text-[11px] text-[#63709A]">{s.date} · {s.durationMinutes} min{s.score?` · ${s.score}`:""}</p></div><ChevronRight className="journal-subject-accent size-4"/></Link>)}{!scoped.length?<p className="p-6 text-xs text-[#63709A]">还没有{label}学习记录。</p>:null}</div></JournalPaper></section>
<div className="flex flex-wrap gap-3"><Link to="/practice" search={meta.practiceSearch} className="journal-subject-button px-5 py-2.5 text-xs font-medium">去{label}学习</Link><Link to="/history" search={{module}} className="border border-[var(--page-subject)] bg-[var(--journal-paper)] px-5 py-2.5 text-xs text-[var(--journal-ink)]">{label}历史</Link><a href={meta.examHref} className="border border-[var(--page-subject)] bg-[var(--journal-paper)] px-5 py-2.5 text-xs text-[var(--journal-ink)]">{meta.examLabel}</a></div></div>}
