import { useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ChevronRight } from "lucide-react";
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from "@/components/ui/sheet";
import { Chip,formatCnDate,PageHeader,SectionTitle,StatusPill,TrendChart } from "@/components/ui-kit";
import { IndexCard, JournalPaper, ReceiptCard } from "@/components/journal-ui";
import { useAppState } from "@/state/app-state";
import type { LearningSignal, Module, SignalStatus, StudySession } from "@/data/mock";
import { keyFromLabel, learningModules } from "@/lib/learning-navigation";
import { cn } from "@/lib/utils";

export const Route=createFileRoute("/progress")({head:()=>({meta:[{title:"进度 · Ivy English"},{name:"description",content:"真实学习记录、IELTS 原始得分、错题、生词与反复出现的学习问题。"}]}),component:ProgressPage});
const ranges=["7天","30天","3个月","全部"] as const;const signalTabs=["全部","听力","口语","阅读","写作"] as const;const signalStatuses:SignalStatus[]=["训练中","正在进步","已稳定"];
const subjectByKey={listening:"listening",speaking:"speaking",reading:"reading",writing:"writing"} as const;
function daysFor(range:string){return range==="7天"?7:range==="30天"?30:range==="3个月"?90:99999}
function filteredByRange(sessions:StudySession[],range:string){const days=daysFor(range);if(days>10000)return sessions;const cutoff=Date.now()-days*86400000;return sessions.filter(s=>new Date(`${s.date}T00:00:00`).getTime()>=cutoff)}
function formatMinutes(total:number){const h=Math.floor(total/60);const m=total%60;return h?`${h}h ${m.toString().padStart(2,"0")}m`:`${m}m`}
function rawScores(sessions:StudySession[],module:"阅读"|"听力"){return sessions.filter(s=>s.module===module&&/^\d+\s*\/\s*\d+/.test(s.score??"")).map(s=>{const match=(s.score??"").match(/(\d+)\s*\/\s*(\d+)/);return match?{session:s,value:Number(match[1]),total:Number(match[2])}:null}).filter(Boolean) as {session:StudySession;value:number;total:number}[]}

function ProgressPage(){const [range,setRange]=useState<(typeof ranges)[number]>("30天");const [signalTab,setSignalTab]=useState<(typeof signalTabs)[number]>("全部");const [active,setActive]=useState<LearningSignal|null>(null);const {sessions,signals,updateSignalStatus,mistakes,vocabulary}=useAppState();const scoped=useMemo(()=>filteredByRange(sessions,range),[sessions,range]);const totalMinutes=scoped.reduce((sum,s)=>sum+s.durationMinutes,0);const skills=learningModules.map(meta=>({meta,minutes:scoped.filter(s=>s.module===meta.label).reduce((sum,s)=>sum+s.durationMinutes,0),count:scoped.filter(s=>s.module===meta.label).length}));const trend=useMemo(()=>{const grouped=new Map<string,number>();[...scoped].reverse().forEach(s=>grouped.set(s.date,(grouped.get(s.date)??0)+s.durationMinutes));return Array.from(grouped.entries()).slice(-12).map(([label,minutes])=>({label:label.slice(5),minutes}))},[scoped]);const filteredSignals=signalTab==="全部"?signals:signals.filter(s=>s.module===signalTab);const selected=active?signals.find(s=>s.id===active.id)??active:null;const readingScores=rawScores(sessions,"阅读");const listeningScores=rawScores(sessions,"听力");
function scoreCard(label:string,values:{session:StudySession;value:number;total:number}[]){const latest=values[0];const five=values.slice(0,5);const avg=five.length?five.reduce((sum,v)=>sum+v.value,0)/five.length:null;const key=label==="Reading"?"reading":"listening";const subject=key==="reading"?"reading":"listening";return <IndexCard subject={subject} className="p-5 pt-7 sm:p-6 sm:pt-8"><p className="text-sm font-medium text-[var(--journal-ink)]">{label}</p><div className="mt-4 space-y-2 text-xs text-[#63709A]"><p>最近：<span className="tabular-nums text-[var(--journal-ink)]">{latest?`${latest.value} / ${latest.total}`:"暂无"}</span></p><p>近 5 次平均：<span className="tabular-nums text-[var(--journal-ink)]">{avg===null?"暂无":`${avg.toFixed(1)} / ${latest?.total??40}`}</span></p></div><Link to="/progress-detail" search={{module:key}} className="subject-text mt-4 inline-flex items-center text-[11px] font-semibold">进入 {label} 分析 <ChevronRight className="ml-1 size-3"/></Link></IndexCard>}
return <div className="journal-page space-y-10"><PageHeader title="进度" subtitle="总览只回答“最近练得怎么样”；点进听说读写后再看每个模块自己的历史、趋势和分析。"/><div className="flex gap-2 overflow-x-auto pb-1">{ranges.map(r=><Chip key={r} active={range===r} onClick={()=>setRange(r)}>{r}</Chip>)}</div>
<ReceiptCard className="p-6 sm:p-8"><div className="grid grid-cols-2 gap-5 sm:grid-cols-4"><div className="journal-stat"><p className="text-[10px] uppercase tracking-[0.1em] text-[#63709A]">{range}学习时间</p><p className="display mt-2 text-2xl text-[var(--journal-ink)]">{formatMinutes(totalMinutes)}</p></div><div className="journal-stat"><p className="text-[10px] uppercase tracking-[0.1em] text-[#63709A]">学习次数</p><p className="display mt-2 text-2xl tabular-nums text-[var(--journal-ink)]">{scoped.length}</p></div><div className="journal-stat"><p className="text-[10px] uppercase tracking-[0.1em] text-[#63709A]">待复习错题</p><p className="display mt-2 text-2xl tabular-nums text-[var(--journal-ink)]">{mistakes.filter(m=>m.status!=="已掌握").length}</p></div><div className="journal-stat"><p className="text-[10px] uppercase tracking-[0.1em] text-[#63709A]">生词</p><p className="display mt-2 text-2xl tabular-nums text-[var(--journal-ink)]">{vocabulary.length}</p></div></div><div className="mt-7 border-t border-[color:var(--journal-line)] pt-5"><p className="mb-3 text-xs text-[#63709A]">学习时间趋势</p>{trend.length?<TrendChart data={trend}/>:<p className="py-8 text-center text-xs text-[#63709A]">这个范围还没有学习记录。</p>}</div></ReceiptCard>
<section><SectionTitle title="听说读写" subtitle="这里是四个分析入口，不再跳回学习页。"/><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{skills.map(({meta,minutes,count})=><Link key={meta.key} to="/progress-detail" search={{module:meta.key}} className={cn(`subject-${meta.key}`,"block")}><IndexCard subject={subjectByKey[meta.key]} className="h-full p-5 pt-7"><p className="text-sm font-medium text-[var(--journal-ink)]">{meta.label}</p><p className="display subject-text mt-4 text-lg tabular-nums">{formatMinutes(minutes)}</p><p className="mt-1 text-[11px] text-[#63709A]">{count} 次记录</p><p className="subject-text mt-4 inline-flex items-center gap-1 text-[11px] font-semibold">查看分析<ChevronRight className="size-3"/></p></IndexCard></Link>)}</div></section>
<section><SectionTitle title="IELTS 表现" subtitle="只记录真实做过的原始得分。"/><div className="grid gap-3 md:grid-cols-2">{scoreCard("Reading",readingScores)}{scoreCard("Listening",listeningScores)}</div></section>
<section><SectionTitle title="复盘与积累"/><div className="grid gap-3 sm:grid-cols-3"><Link to="/mistakes" className="journal-folder p-5"><p className="text-sm font-medium text-[var(--journal-ink)]">错题本</p><p className="display mt-3 text-2xl text-[var(--journal-ink)]">{mistakes.length}</p><p className="mt-1 text-[11px] text-[#63709A]">{mistakes.filter(m=>m.status!=="已掌握").length} 条还需要复习</p></Link><Link to="/vocabulary" className="journal-folder p-5"><p className="text-sm font-medium text-[var(--journal-ink)]">生词本</p><p className="display mt-3 text-2xl text-[var(--journal-ink)]">{vocabulary.length}</p><p className="mt-1 text-[11px] text-[#63709A]">{vocabulary.filter(v=>v.status!=="已掌握").length} 个正在学习</p></Link><Link to="/history" search={{module:"all"}} className="journal-folder p-5"><p className="text-sm font-medium text-[var(--journal-ink)]">学习历史</p><p className="display mt-3 text-2xl text-[var(--journal-ink)]">{sessions.length}</p><p className="mt-1 text-[11px] text-[#63709A]">查看完整题目、回答与材料</p></Link></div></section>
<section><SectionTitle title="我的学习问题"/><div className="mb-4 flex gap-2 overflow-x-auto pb-1">{signalTabs.map(t=><Chip key={t} active={signalTab===t} onClick={()=>setSignalTab(t)}>{t}</Chip>)}</div><JournalPaper tone="yellow" className="overflow-hidden"><div className="divide-y divide-[color:var(--journal-line)]">{filteredSignals.map(s=><button key={s.id} type="button" onClick={()=>setActive(s)} className="journal-list-row flex w-full items-center gap-4 px-5 py-4 text-left"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-[var(--journal-ink)]">{s.title}</p><p className="mt-1 text-[11px] text-[#63709A]">{s.module} · 最近出现 {formatCnDate(s.lastSeen)}</p></div><StatusPill status={s.status}/><ChevronRight className="size-4 text-[#63709A]"/></button>)}{!filteredSignals.length?<p className="px-5 py-8 text-center text-sm text-[#63709A]">这个科目暂时没有记录的问题。</p>:null}</div></JournalPaper></section>
<section><SectionTitle title="最近的学习" action={<Link to="/history" search={{module:"all"}} className="journal-link text-xs">查看全部</Link>}/><ol className="journal-ledger border border-[color:var(--journal-line)] bg-[var(--journal-paper)] px-4 py-2">{sessions.slice(0,12).map(s=>{const moduleKey=keyFromLabel(s.module);return <li key={s.id}><Link to="/session" search={{id:s.id,from:"progress",module:moduleKey}} className="journal-list-row flex gap-5 border-b border-[color:var(--journal-line)] py-3 last:border-b-0"><span className="w-16 shrink-0 pl-2 pt-0.5 text-[11px] tabular-nums text-[#63709A]">{formatCnDate(s.date)}</span><span className="relative flex-1 border-l border-[color:var(--journal-line)] pl-5"><span className="absolute top-1.5 -left-[4px] size-2 bg-[var(--journal-turquoise)]"/><span className="block text-sm font-medium text-[var(--journal-ink)]">{s.activity}</span><span className="mt-1 block text-[11px] text-[#63709A]">{s.module}{s.score?` · ${s.score}`:""} · {s.durationMinutes} min{s.tool?` · ${s.tool}`:""}</span></span><ChevronRight className="mr-2 mt-1 size-4 text-[#63709A]"/></Link></li>})}</ol></section>
<Sheet open={!!selected} onOpenChange={o=>!o&&setActive(null)}><SheetContent className="journal-app w-full overflow-y-auto border-l border-[color:var(--journal-line)] bg-[var(--journal-canvas)] sm:max-w-md">{selected?<><SheetHeader><SheetTitle className="display text-xl leading-snug text-[var(--journal-ink)]">{selected.title}</SheetTitle><SheetDescription className="text-xs text-[#63709A]">{selected.module} · {selected.status}</SheetDescription></SheetHeader><div className="mt-8 space-y-6 pb-8"><JournalPaper tone="paper" className="grid grid-cols-3 gap-3 p-4 text-xs"><div><p className="text-[#63709A]">首次出现</p><p className="mt-1 tabular-nums">{selected.firstSeen}</p></div><div><p className="text-[#63709A]">最近出现</p><p className="mt-1 tabular-nums">{selected.lastSeen}</p></div><div><p className="text-[#63709A]">出现次数</p><p className="mt-1 tabular-nums">{selected.occurrenceCount}</p></div></JournalPaper><div><p className="text-xs text-[#63709A]">表现</p><p className="mt-2 text-sm leading-relaxed text-[var(--journal-body)]">{selected.evidence}</p></div><JournalPaper tone="mint" className="p-4"><p className="text-xs text-[var(--journal-turquoise)]">下一步</p><p className="mt-2 text-sm leading-relaxed">{selected.nextAction}</p></JournalPaper><div><p className="text-xs text-[#63709A]">训练状态</p><div className="mt-3 flex flex-wrap gap-2">{signalStatuses.map(status=><Chip key={status} active={selected.status===status} onClick={()=>updateSignalStatus(selected.id,status)}>{status}</Chip>)}</div></div><div><p className="text-xs text-[#63709A]">相关记录</p><ul className="mt-3 space-y-2">{sessions.filter(s=>selected.relatedSessionIds.includes(s.id)).map(s=>{const key=keyFromLabel(s.module);return <li key={s.id}><Link to="/session" search={{id:s.id,from:"progress",module:key}} className="journal-section-paper block px-4 py-3 text-xs"><p className="text-sm font-medium text-[var(--journal-ink)]">{s.activity}</p><p className="mt-1 text-[#63709A]">{s.date} · {s.durationMinutes} min{s.score?` · ${s.score}`:""}</p></Link></li>})}</ul></div></div></>:null}</SheetContent></Sheet></div>}
