import { useEffect, useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, BarChart3, BookOpenText, ChevronRight, Clock3, Headphones, Mic, PenLine, Target, TrendingUp } from "lucide-react";
import { PageHeader, SectionTitle, TrendChart } from "@/components/ui-kit";
import { useAppState } from "@/state/app-state";
import { listRecordings } from "@/lib/media-store";
import { labelFromKey, moduleMeta, type LearningModuleKey } from "@/lib/learning-navigation";
import type { StudySession } from "@/data/mock";

export const Route=createFileRoute("/progress-detail")({validateSearch:(search:Record<string,unknown>):{module:LearningModuleKey}=>{const valid:LearningModuleKey[]=["listening","speaking","reading","writing"];return{module:valid.includes(search.module as LearningModuleKey)?search.module as LearningModuleKey:"listening"}},head:()=>({meta:[{title:"分项进度 · Ivy English"}]}),component:ProgressDetailPage});

const icons={listening:Headphones,speaking:Mic,reading:BookOpenText,writing:PenLine};
function formatMinutes(total:number){const h=Math.floor(total/60);const m=total%60;return h?`${h}h ${m.toString().padStart(2,"0")}m`:`${m}m`}
function scoreValue(value?:string){const m=value?.match(/(\d+)\s*\/\s*(\d+)/);return m?{value:Number(m[1]),total:Number(m[2])}:null}
function wordValue(value?:string){const m=value?.match(/(\d+)\s*words?/i);return m?Number(m[1]):null}
function isIelts(session:StudySession){return /IELTS|CBT|Task\s*[12]|Speaking Part/i.test(`${session.activity} ${session.tool??""}`)}

function ProgressDetailPage(){const {module}=Route.useSearch();const meta=moduleMeta(module);const label=labelFromKey(module);const Icon=icons[module];const {sessions,mistakes,vocabulary,signals}=useAppState();const scoped=useMemo(()=>sessions.filter(s=>s.module===label),[label,sessions]);const [recordingCount,setRecordingCount]=useState(0);useEffect(()=>{if(module!=="speaking")return;void listRecordings().then(items=>setRecordingCount(items.length)).catch(()=>setRecordingCount(0))},[module]);const totalMinutes=scoped.reduce((sum,s)=>sum+s.durationMinutes,0);const daily=scoped.filter(s=>!isIelts(s));const ielts=scoped.filter(isIelts);const grouped=new Map<string,number>();[...scoped].reverse().forEach(s=>grouped.set(s.date,(grouped.get(s.date)??0)+s.durationMinutes));const trend=Array.from(grouped.entries()).slice(-12).map(([date,minutes])=>({label:date.slice(5),minutes}));const scoreRows=scoped.map(s=>({session:s,score:scoreValue(s.score)})).filter((row):row is {session:StudySession;score:{value:number;total:number}}=>Boolean(row.score));const wordRows=scoped.map(s=>({session:s,words:wordValue(s.score)})).filter((row):row is {session:StudySession;words:number}=>typeof row.words==="number");const avgScore=scoreRows.length?scoreRows.slice(0,5).reduce((sum,row)=>sum+row.score.value,0)/Math.min(5,scoreRows.length):null;const avgWords=wordRows.length?Math.round(wordRows.slice(0,8).reduce((sum,row)=>sum+row.words,0)/Math.min(8,wordRows.length)):null;const moduleMistakes=mistakes.filter(m=>m.module===label);const moduleVocabulary=vocabulary.filter(v=>v.module===label);const moduleSignals=signals.filter(s=>s.module===label);const activityCounts=Object.entries(scoped.reduce<Record<string,number>>((acc,s)=>{acc[s.activity]=(acc[s.activity]??0)+1;return acc},{})).sort((a,b)=>b[1]-a[1]).slice(0,5);
const primaryStat=module==="writing"?`${wordRows.reduce((sum,row)=>sum+row.words,0)} words`:module==="speaking"?`${recordingCount} 录音`:scoreRows[0]?`${scoreRows[0].score.value} / ${scoreRows[0].score.total}`:`${scoped.length} 次`;
return <div className="space-y-9"><Link to="/progress" className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3.5"/>返回进度总览</Link><PageHeader title={`${label}进度`} subtitle={`${meta.english} 的学习投入、历史表现、积累和薄弱项都集中在这里。`}/>
<section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="surface p-5"><Clock3 className="size-4 text-sage"/><p className="mt-4 text-[11px] text-muted-foreground">累计学习</p><p className="display mt-1 text-2xl">{formatMinutes(totalMinutes)}</p></div><div className="surface p-5"><BarChart3 className="size-4 text-sage"/><p className="mt-4 text-[11px] text-muted-foreground">学习记录</p><p className="display mt-1 text-2xl">{scoped.length}</p></div><div className="surface p-5"><Target className="size-4 text-sage"/><p className="mt-4 text-[11px] text-muted-foreground">最近表现</p><p className="display mt-1 text-2xl">{primaryStat}</p></div><div className="surface p-5"><TrendingUp className="size-4 text-sage"/><p className="mt-4 text-[11px] text-muted-foreground">Daily / IELTS</p><p className="display mt-1 text-xl">{daily.length} / {ielts.length}</p></div></section>
<section className="surface p-6"><SectionTitle title="学习时间趋势" subtitle="只读取真实保存的学习记录"/>{trend.length?<TrendChart data={trend}/>:<p className="py-10 text-center text-xs text-muted-foreground">还没有足够记录生成趋势。</p>}</section>
{module==="listening"||module==="reading"?<section><SectionTitle title="IELTS 表现"/><div className="grid gap-3 md:grid-cols-2"><div className="surface p-5"><p className="text-sm">最近原始得分</p><p className="display mt-3 text-2xl">{scoreRows[0]?`${scoreRows[0].score.value} / ${scoreRows[0].score.total}`:"暂无"}</p></div><div className="surface p-5"><p className="text-sm">近 5 次平均</p><p className="display mt-3 text-2xl">{avgScore===null?"暂无":`${avgScore.toFixed(1)} / ${scoreRows[0]?.score.total??40}`}</p></div></div></section>:null}
{module==="writing"?<section><SectionTitle title="写作数据"/><div className="grid gap-3 md:grid-cols-3"><div className="surface p-5"><p className="text-xs text-muted-foreground">累计字数</p><p className="display mt-2 text-2xl">{wordRows.reduce((sum,row)=>sum+row.words,0)}</p></div><div className="surface p-5"><p className="text-xs text-muted-foreground">近 8 篇平均</p><p className="display mt-2 text-2xl">{avgWords??"—"}</p></div><div className="surface p-5"><p className="text-xs text-muted-foreground">有完整字数记录</p><p className="display mt-2 text-2xl">{wordRows.length}</p></div></div></section>:null}
{module==="speaking"?<section><SectionTitle title="口语练习"/><div className="grid gap-3 md:grid-cols-3"><div className="surface p-5"><p className="text-xs text-muted-foreground">历史录音</p><p className="display mt-2 text-2xl">{recordingCount}</p></div><div className="surface p-5"><p className="text-xs text-muted-foreground">开口记录</p><p className="display mt-2 text-2xl">{scoped.length}</p></div><div className="surface p-5"><p className="text-xs text-muted-foreground">累计时长</p><p className="display mt-2 text-2xl">{formatMinutes(totalMinutes)}</p></div></div></section>:null}
<section className="grid gap-4 lg:grid-cols-2"><div><SectionTitle title="练习分布"/><div className="surface divide-y divide-border">{activityCounts.map(([activity,count])=><div key={activity} className="flex items-center justify-between px-5 py-4"><span className="truncate pr-4 text-sm">{activity}</span><span className="text-xs tabular-nums text-muted-foreground">{count} 次</span></div>)}{!activityCounts.length?<p className="p-6 text-xs text-muted-foreground">还没有练习记录。</p>:null}</div></div><div><SectionTitle title="复盘信号"/><div className="surface p-5 text-sm"><div className="flex justify-between"><span>错题</span><span>{moduleMistakes.length}</span></div><div className="mt-3 flex justify-between"><span>生词</span><span>{moduleVocabulary.length}</span></div><div className="mt-3 flex justify-between"><span>学习问题</span><span>{moduleSignals.length}</span></div>{moduleSignals.slice(0,2).map(signal=><p key={signal.id} className="mt-4 rounded-lg bg-secondary/45 p-3 text-xs leading-5 text-muted-foreground">{signal.title}</p>)}</div></div></section>
<section><SectionTitle title="最近的学习" action={<Link to="/history" search={{module}} className="text-xs text-sage-foreground hover:underline">查看全部历史</Link>}/><div className="surface divide-y divide-border overflow-hidden">{scoped.slice(0,10).map(s=><Link key={s.id} to="/session" search={{id:s.id,from:"progress",module}} className="flex items-center gap-4 px-5 py-4 hover:bg-secondary/40"><div className="min-w-0 flex-1"><p className="truncate text-sm">{s.activity}</p><p className="mt-1 text-[11px] text-muted-foreground">{s.date} · {s.durationMinutes} min{s.score?` · ${s.score}`:""}</p></div><ChevronRight className="size-4 text-muted-foreground"/></Link>)}</div></section>
<div className="flex flex-wrap gap-3"><Link to="/practice" search={meta.practiceSearch} className="rounded-full bg-primary px-5 py-2.5 text-xs font-medium text-primary-foreground">去{label}学习</Link><a href={meta.examHref} className="rounded-full border border-border px-5 py-2.5 text-xs">{meta.examLabel}</a></div></div>}
