import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { ChevronRight } from "lucide-react";
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from "@/components/ui/sheet";
import { Chip,formatCnDate,PageHeader,SectionTitle,StatusPill,TrendChart } from "@/components/ui-kit";
import { useAppState } from "@/state/app-state";
import { learningSignals,overviewByRange,skillCardsByRange,studySessions,trendByRange } from "@/data/mock";
import type { LearningSignal } from "@/data/mock";
import { cn } from "@/lib/utils";
export const Route=createFileRoute("/progress")({head:()=>({meta:[{title:"进度 · Ivy English"},{name:"description",content:"学习时间趋势、听说读写四项变化、IELTS 表现记录与反复出现的学习问题。"},{property:"og:title",content:"进度 · Ivy English"},{property:"og:description",content:"不是看你刷了多少题，而是看你的英语正在发生什么变化。"}]}),component:ProgressPage});
const ranges=["7天","30天","3个月","全部"];const signalTabs=["全部","听力","口语","阅读","写作"];
function ProgressPage(){const [range,setRange]=useState("30天");const [signalTab,setSignalTab]=useState("全部");const [active,setActive]=useState<LearningSignal|null>(null);const {sessions}=useAppState();const overview=overviewByRange[range]!;const skills=skillCardsByRange[range]!;const trend=trendByRange[range]!;const signals=signalTab==="全部"?learningSignals:learningSignals.filter(s=>s.module===signalTab);return <div className="space-y-12"><PageHeader title="进度" subtitle="不是看你刷了多少题，而是看你的英语正在发生什么变化。"/><div className="flex gap-2 overflow-x-auto pb-1">{ranges.map(r=><Chip key={r} active={range===r} onClick={()=>setRange(r)}>{r}</Chip>)}</div>
<section className="surface p-6 sm:p-8"><div className="flex flex-wrap gap-x-12 gap-y-4"><div><p className="text-[11px] text-muted-foreground">{overview.caption}学习时间</p><p className="display mt-1 text-2xl">{overview.time}</p></div><div><p className="text-[11px] text-muted-foreground">学习次数</p><p className="display mt-1 text-2xl tabular-nums">{overview.count}</p></div></div><div className="mt-8"><p className="mb-4 text-xs text-muted-foreground">学习时间趋势</p><TrendChart data={trend}/></div></section>
<section><SectionTitle title="听说读写"/><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{skills.map(s=><div key={s.module} className="surface p-5"><p className="text-sm">{s.module}</p><p className="display mt-4 text-lg tabular-nums">{s.time}</p><p className="mt-1 text-[11px] text-muted-foreground">趋势 {s.trend}</p></div>)}</div></section>
<section><SectionTitle title="IELTS 表现" subtitle="只记录做过的原始得分，不换算 band。"/><div className="grid gap-3 md:grid-cols-2"><div className="surface p-5 sm:p-6"><p className="text-sm">Reading</p><div className="mt-4 space-y-2 text-xs text-muted-foreground"><p>最近：<span className="tabular-nums text-foreground">31 / 40</span></p><p>近 5 次平均：<span className="tabular-nums text-foreground">30.4 / 40</span></p></div></div><div className="surface p-5 sm:p-6"><p className="text-sm">Listening</p><div className="mt-4 space-y-2 text-xs text-muted-foreground"><p>最近：<span className="tabular-nums text-foreground">28 / 40</span></p><p>近 5 次平均：<span className="tabular-nums text-foreground">27.2 / 40</span></p></div></div></div></section>
<section><SectionTitle title="我的学习问题"/><div className="mb-4 flex gap-2 overflow-x-auto pb-1">{signalTabs.map(t=><Chip key={t} active={signalTab===t} onClick={()=>setSignalTab(t)}>{t}</Chip>)}</div><div className="surface divide-y divide-border overflow-hidden">{signals.map(s=><button key={s.id} type="button" onClick={()=>setActive(s)} className="flex w-full items-center gap-4 px-5 py-4 text-left transition-colors hover:bg-secondary/50"><div className="min-w-0 flex-1"><p className="truncate text-sm">{s.title}</p><p className="mt-1 text-[11px] text-muted-foreground">{s.module} · 最近出现 {formatCnDate(s.lastSeen)}</p></div><StatusPill status={s.status}/><ChevronRight className="size-4 shrink-0 text-muted-foreground"/></button>)}{signals.length===0?<p className="px-5 py-8 text-center text-sm text-muted-foreground">这个科目暂时没有记录的问题。</p>:null}</div></section>
<section><SectionTitle title="最近的学习"/><ol className="space-y-1">{sessions.slice(0,8).map(s=><li key={s.id} className="flex gap-5 py-3"><span className="w-16 shrink-0 pt-0.5 text-[11px] tabular-nums text-muted-foreground">{formatCnDate(s.date)}</span><span className="relative flex-1 border-l border-border pl-5"><span className={cn("absolute top-1.5 -left-[3.5px] size-[7px] rounded-full bg-sage")}/><span className="block text-sm">{s.activity}</span><span className="mt-1 block text-[11px] text-muted-foreground">{s.module}{s.score?` · ${s.score}`:""} · {s.durationMinutes} min{s.tool?` · ${s.tool}`:""}</span></span></li>)}</ol><p className="mt-4 text-[11px] text-muted-foreground">共 {sessions.length} 条记录</p></section>
<Sheet open={!!active} onOpenChange={o=>!o&&setActive(null)}><SheetContent className="w-full overflow-y-auto sm:max-w-md">{active?<><SheetHeader><SheetTitle className="display text-xl leading-snug">{active.title}</SheetTitle><SheetDescription className="text-xs">{active.module} · {active.status}</SheetDescription></SheetHeader><div className="mt-8 space-y-6 pb-8"><div className="grid grid-cols-3 gap-3 text-xs"><div><p className="text-muted-foreground">首次出现</p><p className="mt-1 tabular-nums">{active.firstSeen}</p></div><div><p className="text-muted-foreground">最近出现</p><p className="mt-1 tabular-nums">{active.lastSeen}</p></div><div><p className="text-muted-foreground">出现次数</p><p className="mt-1 tabular-nums">{active.occurrenceCount}</p></div></div><div><p className="text-xs text-muted-foreground">表现</p><p className="mt-2 text-sm leading-relaxed">{active.evidence}</p></div><div className="rounded-xl bg-sage-soft/70 p-4"><p className="text-xs text-sage-foreground">下一步</p><p className="mt-2 text-sm leading-relaxed">{active.nextAction}</p></div><div><p className="text-xs text-muted-foreground">相关记录</p><ul className="mt-3 space-y-2">{studySessions.filter(s=>active.relatedSessionIds.includes(s.id)).map(s=><li key={s.id} className="rounded-lg border border-border px-4 py-3 text-xs"><p className="text-sm">{s.activity}</p><p className="mt-1 text-muted-foreground">{s.date} · {s.durationMinutes} min{s.score?` · ${s.score}`:""}</p></li>)}</ul></div></div></>:null}</SheetContent></Sheet></div>}