import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Play } from "lucide-react";
import { PageHeader } from "@/components/ui-kit";
import { Button } from "@/components/ui/button";
import { useAppState } from "@/state/app-state";

export const Route=createFileRoute("/question")({validateSearch:(search:Record<string,unknown>):{id:string}=>({id:typeof search.id==="string"?search.id:""}),head:()=>({meta:[{title:"题目详情 · Ivy English"}]}),component:QuestionPage});
const subjectClass:Record<string,string>={听力:"subject-listening journal-subject-listening",口语:"subject-speaking journal-subject-speaking",阅读:"subject-reading journal-subject-reading",写作:"subject-writing journal-subject-writing"};
function href(module:string,part?:string){if(module==="口语")return `/speaking-workspace?mode=${part==="Part 1"?"part1":part==="Part 2"?"part2":part==="Part 3"?"part3":"free"}`;if(module==="写作")return `/writing-exam-v2?mode=familiarisation&scope=${part==="Task 1"?"task1":"task2"}`;if(module==="阅读")return "/exam-v3?mode=familiarisation&scope=passage";return "/listening-exam-v3?mode=familiarisation&scope=section";}
function QuestionPage(){const {id}=Route.useSearch();const {questions,markPracticed}=useAppState();const q=questions.find(item=>item.id===id);if(!q)return <div className="journal-page"><PageHeader title="题目详情" subtitle="没有找到这道题。"/><Link to="/bank" search={{tab:"recent",subject:"全部"}} className="journal-link text-sm">返回题库</Link></div>;const theme=subjectClass[q.module]??"subject-reading journal-subject-reading";return <div className={`${theme} journal-page space-y-7`}><Link to="/bank" search={{tab:q.sourceType==="recent"?"recent":q.sourceType==="official"?"official":"personal",subject:q.module}} className="subject-text inline-flex items-center gap-1.5 text-xs"><ArrowLeft className="size-3.5"/>返回题库</Link><article className="journal-index-card p-6 pt-8 sm:p-8 sm:pt-10"><div className="flex flex-wrap items-center gap-2 text-[11px] text-[#63709A]"><span className="subject-chip px-2.5 py-1">{q.module}</span>{q.part?<span>{q.part}</span>:null}<span>{q.sourceType==="recent"?"考生回忆整理":q.sourceType==="official"?"官方样题入口":"个人题目"}</span></div><h1 className="display mt-5 text-2xl leading-snug text-[var(--journal-ink)] sm:text-3xl">{q.title}</h1>{q.topic.length?<div className="mt-4 flex flex-wrap gap-2">{q.topic.map(t=><span key={t} className="border border-[var(--journal-line)] bg-[var(--journal-paper)] px-2.5 py-1 text-[10px] text-[#63709A]">{t}</span>)}</div>:null}<div className="mt-7 grid gap-3 sm:grid-cols-3">{q.recentDate?<div className="journal-stat"><p className="text-[11px] text-[#63709A]">最近出现</p><p className="mt-1 text-sm text-[var(--journal-ink)]">{q.recentDate}</p></div>:null}{q.reportCount?<div className="journal-stat"><p className="text-[11px] text-[#63709A]">报告次数</p><p className="mt-1 text-sm text-[var(--journal-ink)]">{q.reportCount}</p></div>:null}<div className="journal-stat"><p className="text-[11px] text-[#63709A]">练习状态</p><p className="mt-1 text-sm text-[var(--journal-ink)]">{q.status}</p></div></div>{q.note?<div className="mt-7"><p className="text-xs text-[#63709A]">思路备忘</p><p className="journal-ledger mt-2 border border-[var(--journal-line)] bg-[var(--journal-yellow)] p-4 text-sm leading-7 text-[var(--journal-body)]">{q.note}</p></div>:null}<div className="mt-8 flex flex-wrap gap-3"><a href={href(q.module,q.part)} onClick={()=>markPracticed(q.id)} className="journal-subject-button inline-flex h-10 items-center gap-2 px-5 text-xs font-medium"><Play className="size-3.5"/>开始{q.module==="写作"?"写作":"练习"}</a><Button variant="outline" className="rounded-sm border-[var(--subject-color)] bg-[var(--journal-paper)]" onClick={()=>markPracticed(q.id)}>标记已练习</Button></div></article></div>;}
