import { useEffect, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Mic2, Trash2 } from "lucide-react";
import { PageHeader, SectionTitle } from "@/components/ui-kit";
import { deleteRecording, listRecordings, type SavedRecordingMeta } from "@/lib/media-store";

type Row=SavedRecordingMeta&{url:string};
export const Route=createFileRoute("/recordings")({head:()=>({meta:[{title:"历史录音 · Ivy English"}]}),component:RecordingsPage});
function RecordingsPage(){const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(true);async function load(){setLoading(true);const records=await listRecordings();setRows(old=>{old.forEach(row=>URL.revokeObjectURL(row.url));return records.map(record=>({...record,url:URL.createObjectURL(record.blob)}))});setLoading(false)}useEffect(()=>{void load();return()=>{rows.forEach(row=>URL.revokeObjectURL(row.url))}},[]);async function remove(id:string){await deleteRecording(id);await load()}return <div className="space-y-9"><PageHeader title="历史录音" subtitle="Speaking Workspace 的录音会保存在这台设备的浏览器里。"/><section><SectionTitle title="最近录音" subtitle={loading?"读取中…":`${rows.length} 条`}/><div className="space-y-3">{rows.map(row=><article key={row.id} className="surface p-5 sm:p-6"><div className="flex items-start gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-full bg-sage-soft text-sage-foreground"><Mic2 className="size-4"/></div><div className="min-w-0 flex-1"><p className="text-sm">{row.title}</p><p className="mt-1 text-[11px] text-muted-foreground">{new Date(row.createdAt).toLocaleString("zh-CN")} · {(row.size/1024).toFixed(0)} KB</p><p className="mt-3 line-clamp-2 text-xs leading-5 text-muted-foreground">{row.prompt}</p></div><button type="button" onClick={()=>remove(row.id)} className="text-muted-foreground hover:text-foreground"><Trash2 className="size-4"/></button></div><audio controls src={row.url} className="mt-4 w-full"/></article>)}{!loading&&!rows.length?<div className="surface py-14 text-center"><Mic2 className="mx-auto size-7 text-sage"/><p className="mt-4 text-sm">还没有保存的录音。</p><p className="mt-1 text-xs text-muted-foreground">去 Speaking Workspace 完成一次回答，录音会自动出现在这里。</p></div>:null}</div></section><Link to="/practice" search={{module:"speaking"}} className="text-xs text-sage-foreground hover:underline">返回口语练习</Link></div>}
