import { useEffect, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Mic2, Trash2 } from "lucide-react";
import { PageHeader, SectionTitle } from "@/components/ui-kit";
import { JournalPaper } from "@/components/journal-ui";
import { deleteRecording, listRecordings, type SavedRecordingMeta } from "@/lib/media-store";

type Row=SavedRecordingMeta&{url:string};
export const Route=createFileRoute("/recordings")({head:()=>({meta:[{title:"历史录音 · Ivy English"}]}),component:RecordingsPage});
function modeLabel(mode:string){if(mode==="part1")return"IELTS Part 1";if(mode==="part2")return"IELTS Part 2";if(mode==="part3")return"IELTS Part 3";if(mode==="full")return"IELTS Full";if(mode==="minute")return"一分钟话题";if(mode==="retell")return"复述";if(mode==="image")return"图片描述";if(mode==="today")return"今日话题";return"自由表达"}
function RecordingsPage(){const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(true);async function load(){setLoading(true);const records=await listRecordings();setRows(old=>{old.forEach(row=>URL.revokeObjectURL(row.url));return records.map(record=>({...record,url:URL.createObjectURL(record.blob)}))});setLoading(false)}useEffect(()=>{void load();return()=>{rows.forEach(row=>URL.revokeObjectURL(row.url))}},[]);async function remove(id:string){await deleteRecording(id);await load()}return <div className="journal-page subject-speaking space-y-9"><div className="flex flex-wrap items-center justify-between gap-3"><Link to="/practice" search={{module:"speaking"}} className="subject-text inline-flex items-center gap-1.5 text-xs"><ArrowLeft className="size-3.5"/>返回口语学习</Link><div className="flex gap-3"><Link to="/history" search={{module:"speaking"}} className="subject-text text-xs font-semibold">口语历史</Link><Link to="/progress-detail" search={{module:"speaking"}} className="subject-text text-xs font-semibold">口语进度</Link></div></div><PageHeader title="历史录音" subtitle="每条回答都保留题目、练习类型和可回放音频；录音文件只保存在当前设备浏览器。"/><section><SectionTitle title="最近录音" subtitle={loading?"读取中…":`${rows.length} 条`}/><div className="space-y-4">{rows.map((row,index)=><article key={row.id} className={`journal-index-card subject-speaking p-5 pt-7 sm:p-6 sm:pt-8 ${index%2===0?"md:-rotate-[0.15deg]":"md:rotate-[0.15deg]"}`}><div className="flex items-start gap-3"><Mic2 className="subject-text mt-0.5 size-5 shrink-0" strokeWidth={1.7}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium text-[var(--journal-ink)]">{row.title}</p><span className="subject-chip rounded-sm px-2 py-0.5 text-[10px]">{modeLabel(row.mode)}</span></div><p className="mt-1 text-[11px] text-[#63709A]">{new Date(row.createdAt).toLocaleString("zh-CN")} · {(row.size/1024).toFixed(0)} KB</p><p className="journal-rule mt-3 border border-[color:var(--journal-line)] bg-[var(--journal-paper)] p-3 text-xs leading-6 text-[#52608C]">{row.prompt}</p></div><button type="button" onClick={()=>remove(row.id)} className="text-[#63709A] hover:text-[var(--journal-danger)]"><Trash2 className="size-4"/></button></div><audio controls src={row.url} className="mt-4 w-full accent-[var(--subject-speaking)]"/></article>)}{!loading&&!rows.length?<JournalPaper tone="paper" className="py-14 text-center"><Mic2 className="mx-auto size-7 text-[var(--subject-speaking)]"/><p className="mt-4 text-sm text-[var(--journal-ink)]">还没有保存的录音。</p><p className="mt-1 text-xs text-[#63709A]">去口语学习完成一次回答，录音会自动出现在这里。</p></JournalPaper>:null}</div></section></div>}
