import { useEffect, useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, CheckCircle2, FileText, Headphones, Mic2, RotateCcw, XCircle } from "lucide-react";
import { PageHeader } from "@/components/ui-kit";
import { Button } from "@/components/ui/button";
import { useAppState } from "@/state/app-state";
import { getSessionDetail } from "@/lib/session-detail-store";
import { keyFromLabel, moduleMeta, type LearningModuleKey } from "@/lib/learning-navigation";
import { listRecordings, type SavedRecording } from "@/lib/media-store";

export type SessionFrom="history"|"progress"|"practice"|"library";
export const Route=createFileRoute("/session")({validateSearch:(search:Record<string,unknown>):{id:string;from:SessionFrom;module:LearningModuleKey}=>{const modules:LearningModuleKey[]=["listening","speaking","reading","writing"];const froms:SessionFrom[]=["history","progress","practice","library"];return{id:typeof search.id==="string"?search.id:"",from:froms.includes(search.from as SessionFrom)?search.from as SessionFrom:"history",module:modules.includes(search.module as LearningModuleKey)?search.module as LearningModuleKey:"listening"}},head:()=>({meta:[{title:"学习记录 · Ivy English"}]}),component:SessionPage});

function BackLink({from,module}:{from:SessionFrom;module:LearningModuleKey}){if(from==="progress")return <Link to="/progress-detail" search={{module}} className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3.5"/>返回{moduleMeta(module).label}进度</Link>;if(from==="practice")return <Link to="/practice" search={{module}} className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3.5"/>返回{moduleMeta(module).label}学习</Link>;if(from==="library")return <Link to="/library" className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3.5"/>返回资料库</Link>;return <Link to="/history" search={{module}} className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3.5"/>返回{moduleMeta(module).label}历史</Link>}

function SessionPage(){const {id,from,module:searchModule}=Route.useSearch();const {sessions}=useAppState();const session=sessions.find(s=>s.id===id);const module=session?keyFromLabel(session.module):searchModule;const detail=useMemo(()=>getSessionDetail(id),[id]);const [recordings,setRecordings]=useState<(SavedRecording&{url:string})[]>([]);useEffect(()=>{let mounted=true;void listRecordings().then(items=>{if(!mounted)return;const ids=new Set(detail?.recordingIds??[]);setRecordings(items.filter(item=>ids.has(item.id)).map(item=>({...item,url:URL.createObjectURL(item.blob)})))}).catch(()=>setRecordings([]));return()=>{mounted=false;setRecordings(current=>{current.forEach(item=>URL.revokeObjectURL(item.url));return []})}},[detail?.recordingIds]);if(!session)return <div className="space-y-6"><PageHeader title="学习记录" subtitle="没有找到这条记录。"/><BackLink from={from} module={module}/></div>;const meta=moduleMeta(module);const isIelts=/IELTS|CBT|Task\s*[12]|Exam Engine/i.test(`${session.activity} ${session.tool??""}`);const retryHref=isIelts?meta.examHref:`/practice?module=${module}`;
return <div className="space-y-8"><div className="flex flex-wrap items-center justify-between gap-3"><BackLink from={from} module={module}/><div className="flex gap-3"><Link to="/history" search={{module}} className="text-xs text-sage-foreground hover:underline">{session.module}历史</Link><Link to="/progress-detail" search={{module}} className="text-xs text-sage-foreground hover:underline">{session.module}进度</Link></div></div><div className="surface p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="rounded-full bg-sage-soft px-2.5 py-1 text-[10px] text-sage-foreground">{session.module}</span><h1 className="display mt-4 text-2xl sm:text-3xl">{session.activity}</h1><p className="mt-2 text-xs text-muted-foreground">{session.date}{session.tool?` · ${session.tool}`:""}</p></div>{session.score?<p className="display text-2xl tabular-nums">{session.score}</p>:null}</div><div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-secondary/50 p-4"><p className="text-[11px] text-muted-foreground">学习时间</p><p className="mt-1 text-lg tabular-nums">{session.durationMinutes} min</p></div><div className="rounded-xl bg-secondary/50 p-4"><p className="text-[11px] text-muted-foreground">类型</p><p className="mt-1 text-lg">{detail?.kind==="ielts"||isIelts?"IELTS / CBT":"Daily English"}</p></div><div className="rounded-xl bg-secondary/50 p-4"><p className="text-[11px] text-muted-foreground">结果</p><p className="mt-1 text-lg">{session.score??"已完成"}</p></div></div>
{detail?.prompt?<section className="mt-7"><p className="text-xs text-muted-foreground">题目 / Prompt</p><p className="mt-2 rounded-xl bg-secondary/45 p-4 text-sm leading-6">{detail.prompt}</p></section>:null}
{detail?.sourceTitle||detail?.sourceText?<section className="mt-7"><p className="text-xs text-muted-foreground">学习材料</p><div className="mt-2 rounded-xl border border-border p-4"><div className="flex items-center gap-2 text-sm">{module==="listening"?<Headphones className="size-4 text-sage"/>:<FileText className="size-4 text-sage"/>}<span>{detail.sourceTitle??detail.mediaLabel??"本次材料"}</span></div>{detail.sourceText?<p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{detail.sourceText}</p>:null}</div></section>:null}
{detail?.userResponse?<section className="mt-7"><p className="text-xs text-muted-foreground">你的回答</p><p className="mt-2 whitespace-pre-wrap rounded-xl bg-[#f7f6f1] p-4 text-sm leading-7">{detail.userResponse}</p></section>:session.notes?<section className="mt-7"><p className="text-xs text-muted-foreground">学习内容 / 备注</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{session.notes}</p></section>:null}
{detail?.questions?.length?<section className="mt-7"><p className="text-xs text-muted-foreground">逐题记录</p><div className="mt-3 divide-y divide-border overflow-hidden rounded-xl border border-border">{detail.questions.map((q,index)=><div key={`${q.question}-${index}`} className="grid gap-3 p-4 sm:grid-cols-[42px_1fr_auto]"><span className="flex size-8 items-center justify-center rounded-full bg-secondary text-xs">{q.number??index+1}</span><div><p className="text-sm">{q.question}</p><p className="mt-1 text-xs text-muted-foreground">你的答案：{q.answer||"未作答"}</p>{q.correctAnswer?<p className="mt-1 text-xs text-muted-foreground">正确答案：{q.correctAnswer}</p>:null}</div>{typeof q.isCorrect==="boolean"?<span className={q.isCorrect?"inline-flex items-center gap-1 text-xs text-sage-foreground":"inline-flex items-center gap-1 text-xs text-amber-700"}>{q.isCorrect?<CheckCircle2 className="size-3.5"/>:<XCircle className="size-3.5"/>}{q.isCorrect?"正确":"错误"}</span>:null}</div>)}</div></section>:null}
{recordings.length?<section className="mt-7"><p className="text-xs text-muted-foreground">本次录音</p><div className="mt-3 space-y-3">{recordings.map(recording=><div key={recording.id} className="rounded-xl border border-border p-4"><div className="flex items-center gap-2"><Mic2 className="size-4 text-sage"/><p className="text-sm">{recording.title}</p></div><p className="mt-2 text-xs text-muted-foreground">{recording.prompt}</p><audio controls src={recording.url} className="mt-3 w-full"/></div>)}</div></section>:detail?.recordingIds?.length?<p className="mt-6 text-xs text-muted-foreground">本次录音已登记，但当前设备没有找到对应音频文件。</p>:null}
{detail?.highlights?.length||detail?.vocabulary?.length?<section className="mt-7 grid gap-4 md:grid-cols-2">{detail.highlights?.length?<div><p className="text-xs text-muted-foreground">Highlights</p><div className="mt-2 space-y-2">{detail.highlights.map((item,index)=><p key={`${item}-${index}`} className="rounded-lg bg-[#fff8bf] px-3 py-2 text-xs">{item}</p>)}</div></div>:null}{detail.vocabulary?.length?<div><p className="text-xs text-muted-foreground">Vocabulary</p><div className="mt-2 flex flex-wrap gap-2">{detail.vocabulary.map((word,index)=><span key={`${word}-${index}`} className="rounded-full bg-sage-soft px-2.5 py-1 text-xs text-sage-foreground">{word}</span>)}</div></div>:null}</section>:null}
<div className="mt-8 flex flex-wrap gap-3"><a href={retryHref} className="inline-flex h-10 items-center gap-2 rounded-full bg-primary px-4 text-xs font-medium text-primary-foreground"><RotateCcw className="size-3.5"/>再练一次</a><Button asChild variant="outline" className="rounded-full"><Link to="/history" search={{module}}>查看{session.module}历史</Link></Button>{module==="speaking"?<Button asChild variant="outline" className="rounded-full"><Link to="/recordings">全部录音</Link></Button>:null}</div></div></div>}
