import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Clock3, RotateCcw } from "lucide-react";
import { PageHeader } from "@/components/ui-kit";
import { Button } from "@/components/ui/button";
import { useAppState } from "@/state/app-state";

export const Route=createFileRoute("/session")({validateSearch:(search:Record<string,unknown>):{id:string}=>({id:typeof search.id==="string"?search.id:""}),head:()=>({meta:[{title:"学习记录 · Ivy English"}]}),component:SessionPage});
function retry(module:string){if(module==="阅读")return "/exam-v3?mode=familiarisation&scope=passage";if(module==="听力")return "/listening-exam-v3?mode=familiarisation&scope=section";if(module==="写作")return "/writing-exam-v2?mode=familiarisation&scope=task2";if(module==="口语")return "/speaking-workspace?mode=free";return "/vocabulary";}
function SessionPage(){const {id}=Route.useSearch();const {sessions}=useAppState();const session=sessions.find(s=>s.id===id);if(!session)return <div className="space-y-6"><PageHeader title="学习记录" subtitle="没有找到这条记录。"/><Link to="/progress" className="text-sm text-sage-foreground hover:underline">返回进度</Link></div>;return <div className="space-y-8"><Link to="/progress" className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3.5"/>返回进度</Link><div className="surface p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="rounded-full bg-sage-soft px-2.5 py-1 text-[10px] text-sage-foreground">{session.module}</span><h1 className="display mt-4 text-2xl sm:text-3xl">{session.activity}</h1><p className="mt-2 text-xs text-muted-foreground">{session.date}{session.tool?` · ${session.tool}`:""}</p></div>{session.score?<p className="display text-2xl tabular-nums">{session.score}</p>:null}</div><div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-secondary/50 p-4"><p className="text-[11px] text-muted-foreground">学习时间</p><p className="mt-1 text-lg tabular-nums">{session.durationMinutes} min</p></div><div className="rounded-xl bg-secondary/50 p-4"><p className="text-[11px] text-muted-foreground">科目</p><p className="mt-1 text-lg">{session.module}</p></div><div className="rounded-xl bg-secondary/50 p-4"><p className="text-[11px] text-muted-foreground">结果</p><p className="mt-1 text-lg">{session.score??"未记录"}</p></div></div>{session.notes?<div className="mt-6"><p className="text-xs text-muted-foreground">备注</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{session.notes}</p></div>:null}<div className="mt-8 flex gap-3"><a href={retry(session.module)} className="inline-flex h-10 items-center gap-2 rounded-full bg-primary px-4 text-xs font-medium text-primary-foreground"><RotateCcw className="size-3.5"/>再练一次</a><Button asChild variant="outline" className="rounded-full"><Link to="/mistakes">查看错题</Link></Button></div></div></div>;}
