import { useEffect, useRef, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, Check, ChevronLeft, Mic, Pause, Pencil, Play, RefreshCw, RotateCcw, Shuffle, Square, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useAppState } from "@/state/app-state";
import { saveRecording } from "@/lib/media-store";
import { saveSessionDetail } from "@/lib/session-detail-store";
import { cn } from "@/lib/utils";

type Mode="free"|"minute"|"retell"|"image"|"today"|"part1"|"part2"|"part3"|"full";
type Prompt={id:string;text:string;part?:"Part 1"|"Part 2"|"Part 3";prep?:number;answer?:number};
export const Route=createFileRoute("/speaking-workspace")({validateSearch:(search:Record<string,unknown>):{mode:Mode}=>{const modes:Mode[]=["free","minute","retell","image","today","part1","part2","part3","full"];return{mode:modes.includes(search.mode as Mode)?search.mode as Mode:"free"}},head:()=>({meta:[{title:"Speaking Workspace · Ivy English"}]}),component:SpeakingWorkspace});
const p=(id:string,text:string,answer?:number,prep?:number,part?:Prompt["part"]):Prompt=>({id,text,...(answer?{answer}:{}),...(prep?{prep}:{}),...(part?{part}:{})});
const pools={
free:[p("free-1","What is on your mind today?"),p("free-2","Tell me about something you have been thinking about recently."),p("free-3","What would you like to explain in English today?")],
minute:[p("minute-1","What is one small thing that made your week better?",60),p("minute-2","Describe a habit that makes your day easier.",60),p("minute-3","What is a place where you can concentrate well?",60),p("minute-4","Talk about a decision you made quickly and why.",60)],
retell:[p("retell-1","A student missed an early train, changed her route, and unexpectedly found a quiet café where she finished an assignment. Retell the story in your own words.",90),p("retell-2","A small neighbourhood bookshop started opening late on Fridays. Students began using the back room to study, and the owner noticed that people often stayed to discuss the books they had found. Retell the story in your own words.",90),p("retell-3","Two friends planned a day at the beach, but heavy rain changed their plans. They visited a local museum instead and discovered an exhibition they had wanted to see for months. Retell the story in your own words.",90)],
today:[p("today-1","Would you rather have a very planned week or leave more room for spontaneous decisions? Why?"),p("today-2","What is something you have changed your mind about recently?"),p("today-3","Which part of your daily routine feels most like your own time?"),p("today-4","What kind of place makes you want to stay longer than you planned?")],
part1:[p("p1-1","Do you enjoy the place where you live?",45,undefined,"Part 1"),p("p1-2","What do you usually do at weekends?",45,undefined,"Part 1"),p("p1-3","Do you often change your plans?",45,undefined,"Part 1"),p("p1-4","Do you prefer studying alone or with other people?",45,undefined,"Part 1"),p("p1-5","Is there a colour you often choose for clothes?",45,undefined,"Part 1"),p("p1-6","Do you enjoy taking photographs?",45,undefined,"Part 1")],
part2:[p("p2-1","Describe a place you would like to visit again. You should say where it is, when you went there, what you did there, and explain why you would like to return.",120,60,"Part 2"),p("p2-2","Describe a person who helped you learn something important. You should say who the person is, what you learned, how they helped you, and explain why you remember it.",120,60,"Part 2"),p("p2-3","Describe a time when you changed a plan. You should say what the original plan was, why you changed it, what happened, and explain how you felt about the change.",120,60,"Part 2")],
part3:[p("p3-1","Why do some people enjoy returning to the same places?",60,undefined,"Part 3"),p("p3-2","How has travel changed in recent years?",60,undefined,"Part 3"),p("p3-3","Can travelling help people understand themselves better?",60,undefined,"Part 3"),p("p3-4","Why are some people more comfortable with changing plans than others?",60,undefined,"Part 3"),p("p3-5","Should universities encourage students to study subjects outside their main field?",60,undefined,"Part 3")]
};
const configs:Record<Mode,{title:string;subtitle:string}>={free:{title:"自由表达",subtitle:"不限时。按下录音后正向计时，想说多久都可以。"},minute:{title:"一分钟话题",subtitle:"随机换题，也可以自己出题；回答 60 秒。"},retell:{title:"复述练习",subtitle:"可以换文本，也可以粘贴自己的材料再复述。"},image:{title:"图片描述",subtitle:"换一张图片或上传自己的图片，再按整体—细节—推测描述。"},today:{title:"今日话题",subtitle:"随机换一个自然表达题，也可以自己输入今天真正想聊的问题。"},part1:{title:"IELTS Speaking · Part 1",subtitle:"完成一题亮一题；题目可自由切换和更换。"},part2:{title:"IELTS Speaking · Part 2",subtitle:"1 分钟准备，最多 2 分钟回答；可以更换 Cue Card。"},part3:{title:"IELTS Speaking · Part 3",subtitle:"完成一题亮一题；可以自由选择问题。"},full:{title:"IELTS Speaking · Full Simulation",subtitle:"Part 1 → Part 2 → Part 3，保留题号进度与 Part 2 准备时间。"}};
function format(seconds:number){const safe=Math.max(0,Math.floor(seconds));return `${Math.floor(safe/60).toString().padStart(2,"0")}:${(safe%60).toString().padStart(2,"0")}`}
function isIelts(mode:Mode){return ["part1","part2","part3","full"].includes(mode)}
function initialPrompts(mode:Mode):Prompt[]{if(mode==="part1")return pools.part1.slice(0,3);if(mode==="part2")return pools.part2.slice(0,1);if(mode==="part3")return pools.part3.slice(0,3);if(mode==="full")return [pools.part1[0]!,pools.part1[1]!,pools.part2[0]!,pools.part3[0]!,pools.part3[1]!];if(mode==="minute")return [pools.minute[0]!];if(mode==="retell")return [pools.retell[0]!];if(mode==="today")return [pools.today[0]!];if(mode==="free")return [pools.free[0]!];return [p("image-1","Describe the image. Start with the overall scene, then give details and make one reasonable inference.",90)]}

function SpeakingWorkspace(){const {mode}=Route.useSearch();const config=configs[mode];const {addSession}=useAppState();const [prompts,setPrompts]=useState<Prompt[]>(()=>initialPrompts(mode));const [promptIndex,setPromptIndex]=useState(0);const current=prompts[promptIndex]??prompts[0]!;const [completed,setCompleted]=useState<string[]>([]);const [phase,setPhase]=useState<"idle"|"prep"|"answer"|"done">("idle");const [seconds,setSeconds]=useState(0);const [running,setRunning]=useState(false);const [recording,setRecording]=useState(false);const [audioUrl,setAudioUrl]=useState<string|null>(null);const [permissionError,setPermissionError]=useState("");const [savedNotice,setSavedNotice]=useState("");const [savedSessionId,setSavedSessionId]=useState("");const [customOpen,setCustomOpen]=useState(false);const [customText,setCustomText]=useState("");const [imageSeed,setImageSeed]=useState(1);const [uploadedImage,setUploadedImage]=useState<string|null>(null);const recorderRef=useRef<MediaRecorder|null>(null);const streamRef=useRef<MediaStream|null>(null);const chunksRef=useRef<Blob[]>([]);const segmentStartedRef=useRef<number|null>(null);const totalSecondsRef=useRef(0);const recordingIdsRef=useRef<string[]>([]);const activePromptRef=useRef(current.text);const stoppingRef=useRef<Promise<string|null>|null>(null);const imageUrl=uploadedImage??`https://picsum.photos/seed/ivy-speaking-${imageSeed}/1000/680`;
useEffect(()=>{setPrompts(initialPrompts(mode));setPromptIndex(0);setCompleted([]);setPhase("idle");setSeconds(0);setRunning(false);setSavedSessionId("");setCustomOpen(false);setCustomText("");recordingIdsRef.current=[];totalSecondsRef.current=0},[mode]);
useEffect(()=>()=>{streamRef.current?.getTracks().forEach(track=>track.stop())},[]);
useEffect(()=>()=>{if(uploadedImage)URL.revokeObjectURL(uploadedImage)},[uploadedImage]);
async function ensureStream(){if(streamRef.current?.active)return streamRef.current;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;setPermissionError("");return stream}catch{setPermissionError("没有获得麦克风权限。请在浏览器地址栏允许麦克风后重试；计时和换题仍然可以使用。");return null}}
function replaceAudioUrl(next:string|null){setAudioUrl(prev=>{if(prev)URL.revokeObjectURL(prev);return next})}
function accountSegment(){if(segmentStartedRef.current){totalSecondsRef.current+=Math.max(0,Math.round((Date.now()-segmentStartedRef.current)/1000));segmentStartedRef.current=null}}
async function startRecorder(){const stream=await ensureStream();if(!stream)return;const existing=recorderRef.current;if(existing?.state==="recording")return;if(existing?.state==="paused"){existing.resume();segmentStartedRef.current=Date.now();setRecording(true);return}chunksRef.current=[];const recorder=new MediaRecorder(stream);recorderRef.current=recorder;activePromptRef.current=current.text;recorder.ondataavailable=e=>{if(e.data.size)chunksRef.current.push(e.data)};recorder.start(250);segmentStartedRef.current=Date.now();setRecording(true);setSavedNotice("")}
async function stopRecorderAndSave(){if(stoppingRef.current)return stoppingRef.current;const recorder=recorderRef.current;if(!recorder||recorder.state==="inactive"){accountSegment();setRecording(false);return null}accountSegment();const promise=new Promise<string|null>((resolve)=>{recorder.onstop=()=>{const blob=new Blob(chunksRef.current,{type:recorder.mimeType||"audio/webm"});if(!blob.size){setRecording(false);resolve(null);return}replaceAudioUrl(URL.createObjectURL(blob));void saveRecording(blob,{title:config.title,mode,prompt:activePromptRef.current}).then(id=>{recordingIdsRef.current=[...recordingIdsRef.current,id];setSavedNotice("录音已保存到历史录音");setRecording(false);resolve(id)}).catch(()=>{setSavedNotice("录音生成成功，但保存到历史录音失败。");setRecording(false);resolve(null)})};recorder.stop()});stoppingRef.current=promise;const id=await promise;stoppingRef.current=null;return id}
async function discardRecorder(){const recorder=recorderRef.current;accountSegment();if(!recorder||recorder.state==="inactive"){setRecording(false);return}await new Promise<void>(resolve=>{recorder.onstop=()=>{chunksRef.current=[];setRecording(false);resolve()};recorder.stop()})}
function pauseRecorder(){const recorder=recorderRef.current;if(recorder?.state==="recording"){recorder.pause();accountSegment();setRecording(false)}}
async function begin(){setSavedSessionId("");replaceAudioUrl(null);if(current.prep){setPhase("prep");setSeconds(current.prep);setRunning(true);return}setPhase("answer");setSeconds(current.answer??0);setRunning(true);await startRecorder()}
function pause(){setRunning(false);pauseRecorder()}function resume(){setRunning(true);if(phase==="answer")void startRecorder()}
async function completeCurrent(){setRunning(false);await stopRecorderAndSave();setCompleted(prev=>prev.includes(current.id)?prev:[...prev,current.id]);setPhase("done")}
async function reset(){setRunning(false);await discardRecorder();setPhase("idle");setSeconds(0);replaceAudioUrl(null);setSavedNotice("已重置，刚才未完成的录音没有保存。")}
useEffect(()=>{if(!running)return;const timer=window.setInterval(()=>{if(phase==="prep"||current.answer)setSeconds(value=>Math.max(0,value-1));else if(phase==="answer")setSeconds(value=>value+1)},1000);return()=>window.clearInterval(timer)},[current.answer,phase,running]);
useEffect(()=>{if(!running||seconds!==0)return;if(phase==="prep"){setPhase("answer");setSeconds(current.answer??0);void startRecorder()}else if(phase==="answer"&&current.answer){void completeCurrent()}},[current.answer,phase,running,seconds]);
function chooseQuestion(index:number){if(recording||phase==="answer"||phase==="prep")return;setPromptIndex(index);setPhase("idle");setSeconds(0);replaceAudioUrl(null);setSavedNotice("")}
function nextQuestion(){chooseQuestion(Math.min(prompts.length-1,promptIndex+1))}
function poolForCurrent():Prompt[]{if(current.part==="Part 1")return pools.part1;if(current.part==="Part 2")return pools.part2;if(current.part==="Part 3")return pools.part3;if(mode==="minute")return pools.minute;if(mode==="retell")return pools.retell;if(mode==="today")return pools.today;if(mode==="free")return pools.free;return []}
function changePrompt(){if(recording)return;const pool=poolForCurrent();if(!pool.length)return;const currentIndex=pool.findIndex(item=>item.id===current.id);const next=pool[(currentIndex+1+pool.length)%pool.length]!;setPrompts(prev=>prev.map((item,index)=>index===promptIndex?next:item));setPhase("idle");setSeconds(0);replaceAudioUrl(null);setSavedNotice("")}
function useCustom(){const value=customText.trim();if(!value)return;const replacement:Prompt={id:`custom-${Date.now()}`,text:value,...(mode==="minute"?{answer:60}:mode==="retell"?{answer:90}:{})};setPrompts(prev=>prev.map((item,index)=>index===promptIndex?replacement:item));setCustomOpen(false);setPhase("idle");setSeconds(0);setSavedNotice("")}
function changeImage(){if(uploadedImage){URL.revokeObjectURL(uploadedImage);setUploadedImage(null)}setImageSeed(value=>value+1);setPhase("idle");setSavedNotice("")}
function uploadImage(file:File|null){if(!file)return;if(uploadedImage)URL.revokeObjectURL(uploadedImage);setUploadedImage(URL.createObjectURL(file));setPhase("idle");setSavedNotice("")}
async function savePractice(){if(savedSessionId||(!completed.length&&phase==="idle"))return;if(phase==="answer"||recording)await completeCurrent();const doneIds=completed.includes(current.id)?completed:[...completed,current.id];const answeredPrompts=prompts.filter(item=>doneIds.includes(item.id));const duration=Math.max(1,Math.round(totalSecondsRef.current/60));const sessionId=addSession({date:new Date().toISOString().slice(0,10),module:"口语",activity:config.title,tool:"Ivy Speaking Workspace",durationMinutes:duration,score:`${answeredPrompts.length} prompts`,notes:answeredPrompts.map((item,index)=>`${index+1}. ${item.text}`).join("\n")});saveSessionDetail({sessionId,kind:isIelts(mode)?"ielts":"daily",subtype:mode,completedAt:new Date().toISOString(),prompt:answeredPrompts.map((item,index)=>`${index+1}. ${item.text}`).join("\n\n"),recordingIds:[...recordingIdsRef.current],metrics:{promptsCompleted:answeredPrompts.length,recordingSeconds:totalSecondsRef.current},...(mode==="image"?{sourceTitle:"Image description",mediaLabel:uploadedImage?"User uploaded image":`Random practice image ${imageSeed}`}:{})});setSavedSessionId(sessionId);setRunning(false);setPhase("done")}
const timed=Boolean(current.answer);const statusLabel=phase==="prep"?"Preparation":phase==="answer"?(timed?"Answer countdown":"Answer time"):phase==="done"?"Completed":"Ready";const ielts=isIelts(mode);const saveDisabled=Boolean(savedSessionId)||(!completed.length&&phase==="idle");
return <div className="min-h-screen bg-[#f4f1ea] text-[#262a27]"><div className="mx-auto flex min-h-screen max-w-5xl flex-col px-5 py-6 sm:px-8"><header className="flex flex-wrap items-center justify-between gap-3"><Link to="/practice" search={{module:"speaking"}} className="inline-flex items-center gap-1.5 text-xs text-[#66706a]"><ChevronLeft className="size-4"/>返回口语学习</Link><div className="flex items-center gap-3"><Link to="/history" search={{module:"speaking"}} className="text-[11px] text-[#617067] underline underline-offset-4">口语历史</Link><Link to="/progress-detail" search={{module:"speaking"}} className="text-[11px] text-[#617067] underline underline-offset-4">口语进度</Link>{!ielts?<a href="/speaking-workspace?mode=full" className="inline-flex items-center gap-1 rounded-full bg-[#2e3e33] px-3 py-1.5 text-[11px] text-white"><ArrowUpRight className="size-3"/>模拟考试</a>:null}</div></header>
{savedSessionId?<section className="mt-6 rounded-2xl border border-[#b9cbbd] bg-[#eef5ef] p-5"><div className="flex gap-3"><div className="flex size-9 items-center justify-center rounded-full bg-white text-[#42604a]"><Check className="size-4"/></div><div><p className="text-sm font-medium">本次口语练习已保存</p><p className="mt-1 text-xs text-[#68746b]">{completed.length||1} 个话题 · 录音已关联到学习记录</p><div className="mt-4 flex flex-wrap gap-2"><Link to="/session" search={{id:savedSessionId,from:"practice",module:"speaking"}} className="rounded-full bg-[#2e3e33] px-4 py-2 text-xs text-white">查看本次记录</Link><Link to="/history" search={{module:"speaking"}} className="rounded-full border border-[#b8c4ba] px-4 py-2 text-xs">口语历史</Link></div></div></div></section>:null}
<main className="grid flex-1 items-center gap-8 py-8 lg:grid-cols-[0.92fr_1.08fr]"><section><p className="text-xs uppercase tracking-[0.18em] text-[#758079]">Speaking Workspace</p><h1 className="mt-2 font-serif text-3xl leading-tight">{config.title}</h1><p className="mt-2 text-sm leading-6 text-[#687069]">{config.subtitle}</p>
{ielts?<div className="mt-6"><p className="text-[11px] text-[#7b817d]">Questions</p><div className="mt-2 flex flex-wrap gap-2">{prompts.map((item,index)=>{const done=completed.includes(item.id);return <button key={`${item.id}-${index}`} type="button" onClick={()=>chooseQuestion(index)} disabled={recording||phase==="prep"||phase==="answer"} className={cn("min-w-10 rounded-full border px-3 py-2 text-xs transition-colors",done?"border-[#8fb09a] bg-[#dcebdd] text-[#36543f]":index===promptIndex?"border-[#344b3b] bg-[#344b3b] text-white":"border-[#cbc9c1] bg-white")}>{done?"✓ ":""}{index+1}</button>})}</div></div>:null}
<div className="mt-7 rounded-2xl border border-[#d6d4cc] bg-white/75 p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><p className="text-[11px] text-[#7d817d]">{current.part?`${current.part} · `:""}{ielts?`Question ${promptIndex+1} / ${prompts.length}`:"Your prompt"}</p><div className="flex gap-1">{mode!=="image"?<button type="button" onClick={changePrompt} disabled={recording} className="inline-flex items-center gap-1 rounded-full border border-[#d0d2cc] px-2.5 py-1 text-[10px]"><Shuffle className="size-3"/>换一个</button>:null}{!ielts&&mode!=="image"?<button type="button" onClick={()=>setCustomOpen(v=>!v)} className="inline-flex items-center gap-1 rounded-full border border-[#d0d2cc] px-2.5 py-1 text-[10px]"><Pencil className="size-3"/>自己输入</button>:null}</div></div>{mode==="retell"?<div className="mt-3 rounded-xl bg-[#f5f4ef] p-4"><p className="text-[11px] text-[#7b817d]">Retell material</p><p className="mt-2 text-sm leading-7">{current.text.replace(/ Retell the story in your own words\.$/,"")}</p></div>:<p className="mt-3 text-lg leading-8">{current.text}</p>}{customOpen?<div className="mt-4 border-t border-[#e2e0d9] pt-4"><Textarea value={customText} onChange={event=>setCustomText(event.target.value)} rows={3} placeholder={mode==="retell"?"粘贴你想复述的文本...":"输入你想回答的问题..."}/><div className="mt-2 flex justify-end"><Button size="sm" onClick={useCustom} className="rounded-full">使用这个题目</Button></div></div>:null}</div>
{mode==="image"?<div className="mt-5 overflow-hidden rounded-2xl border border-[#d6d4cc] bg-white"><img src={imageUrl} alt="Speaking description practice" className="aspect-[3/2] w-full object-cover"/><div className="flex flex-wrap gap-2 p-3"><button type="button" onClick={changeImage} className="inline-flex items-center gap-1 rounded-full border border-[#d0d2cc] px-3 py-1.5 text-[11px]"><RefreshCw className="size-3"/>换一张图片</button><label className="inline-flex cursor-pointer items-center gap-1 rounded-full border border-[#d0d2cc] px-3 py-1.5 text-[11px]"><Upload className="size-3"/>上传自己的图片<input type="file" accept="image/*" className="hidden" onChange={event=>uploadImage(event.target.files?.[0]??null)}/></label></div></div>:null}
{permissionError?<p className="mt-4 rounded-xl bg-[#fff0dd] p-3 text-xs leading-5 text-[#855b20]">{permissionError}</p>:null}</section>
<section className="rounded-3xl border border-[#d8d5cc] bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start justify-between"><div><p className="text-xs text-[#777e79]">{statusLabel}</p><p className="mt-2 font-mono text-5xl tabular-nums">{format(seconds)}</p><p className="mt-2 text-[11px] text-[#8a908b]">{phase==="answer"&&!timed?"正向计时，不会自动结束":""}</p></div><span className={cn("rounded-full px-3 py-1 text-[10px]",recording?"bg-[#f6dfdc] text-[#8c4037]":completed.includes(current.id)?"bg-[#dfeadf] text-[#48614f]":"bg-[#edf0ec] text-[#66706a]")}>{recording?"RECORDING":completed.includes(current.id)?"DONE":phase==="prep"?"PREPARING":"MIC READY"}</span></div><div className="mt-8 flex flex-wrap items-center gap-3">{phase==="idle"?<Button onClick={()=>void begin()} className="rounded-full px-5"><Mic className="mr-2 size-4"/>{current.prep?"开始准备":"开始回答"}</Button>:null}{running?<Button variant="outline" onClick={pause} className="rounded-full"><Pause className="mr-2 size-4"/>暂停</Button>:phase!=="idle"&&phase!=="done"?<Button onClick={resume} className="rounded-full"><Play className="mr-2 size-4"/>继续</Button>:null}{phase!=="idle"&&phase!=="done"?<Button variant="outline" onClick={()=>void completeCurrent()} className="rounded-full"><Square className="mr-2 size-3.5"/>完成本题</Button>:null}<Button variant="outline" onClick={()=>void reset()} className="rounded-full"><RotateCcw className="mr-2 size-4"/>重置</Button></div>{savedNotice?<p className="mt-4 text-xs text-[#52705b]">{savedNotice}</p>:null}{audioUrl?<div className="mt-7 rounded-2xl bg-[#f5f5f1] p-4"><p className="mb-2 text-xs text-[#6c746e]">刚刚的录音</p><audio controls src={audioUrl} className="w-full"/></div>:null}
<div className="mt-7 flex flex-wrap items-center justify-between gap-3 border-t border-[#e3e1da] pt-5"><div className="text-xs text-[#777e79]">已完成 {completed.length} / {prompts.length}</div><div className="flex gap-2">{phase==="done"&&promptIndex<prompts.length-1?<button type="button" onClick={nextQuestion} className="rounded-full border border-[#cfcfc8] px-4 py-2 text-xs">下一题</button>:null}<Button onClick={()=>void savePractice()} disabled={saveDisabled} className="rounded-full">{savedSessionId?<><Check className="mr-2 size-4"/>已保存</>:"保存本次练习"}</Button></div></div></section></main></div></div>}
