import { useEffect, useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, Check, ChevronLeft, Highlighter, Link2, Pause, Play, RotateCcw, Save, Shuffle, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { DailyAudioPlayer } from "@/components/DailyAudioPlayer";
import { useAppState } from "@/state/app-state";
import { saveSessionDetail } from "@/lib/session-detail-store";
import { moduleMeta, type LearningModuleKey } from "@/lib/learning-navigation";

type Mode="video"|"dictation"|"shadowing"|"graded"|"article"|"academic"|"saved"|"material"|"free-writing"|"journal"|"opinion";
export const Route=createFileRoute("/study-workspace")({validateSearch:(search:Record<string,unknown>):{mode:Mode}=>{const modes:Mode[]=["video","dictation","shadowing","graded","article","academic","saved","material","free-writing","journal","opinion"];return{mode:modes.includes(search.mode as Mode)?search.mode as Mode:"article"}},head:()=>({meta:[{title:"Daily Study Workspace · Ivy English"}]}),component:StudyWorkspace});
const listeningModes=new Set<Mode>(["video","dictation","shadowing","graded"]);const readingModes=new Set<Mode>(["article","academic","saved","material"]);
const listeningPool=[
  {title:"A quiet city morning",text:"On weekday mornings, the first hour of a city can sound completely different from the rest of the day. Delivery bicycles pass quiet cafés, cleaners finish their shifts, and commuters begin to fill the pavements."},
  {title:"Choosing a study place",text:"Some students work best in complete silence, while others prefer the soft noise of a café. The useful question is not which place looks productive, but which environment helps you return to the task after your attention drifts."},
  {title:"Small travel decisions",text:"A good day trip often depends on a few small decisions made early. Checking the last train, carrying water, and leaving some time unplanned can make the day feel both safer and more spontaneous."},
];
const sampleReading={article:{title:"Why quiet routines can help learning",text:"A routine does not have to be rigid to be useful. Researchers who study learning habits often distinguish between repetition and predictability. Repetition means doing the same thing again; predictability means reducing the number of decisions needed before a useful action begins. A student may read a different article every day, for example, while still using the same chair, time window and note-taking ritual. The material changes, but the path into the activity becomes familiar. This can make it easier to begin, especially on days when motivation is low."},academic:{title:"Attention and environmental cues",text:"Environmental cues can influence the transition between intention and action. In educational settings, consistent contextual signals may reduce the cognitive cost of task initiation. This does not imply that a learner should remove all variation. Instead, stable cues can coexist with varied content, allowing practice to remain flexible while the conditions that support concentration become increasingly automatic."},saved:{title:"Saved reading · sample",text:"This area will show webpages you save to Ivy English. Until you add your own links, this short sample lets the reading workspace remain usable."},material:{title:"My material · sample",text:"Materials added in the Library can be read here later. The current V1 keeps PDF metadata locally and uses this workspace for notes, vocabulary and study logging."}} as const;
const writingPrompt:Record<"free-writing"|"journal"|"opinion",string>={"free-writing":"Write whatever you want to put into English today.",journal:"What happened today that you would like to remember?",opinion:"Should university students be encouraged to take more courses outside their main subject?"};
const labels:Record<Mode,string>={video:"真实视频听力",dictation:"盲听与听写",shadowing:"Shadowing",graded:"分级听力",article:"文章阅读",academic:"学术文章",saved:"保存的网页",material:"我的材料","free-writing":"自由写作",journal:"日记",opinion:"观点表达"};
function format(s:number){return `${Math.floor(s/60).toString().padStart(2,"0")}:${(s%60).toString().padStart(2,"0")}`}

function StudyWorkspace(){const {mode}=Route.useSearch();const {addSession,addVocabulary,libraryItems}=useAppState();const isListening=listeningModes.has(mode);const isReading=readingModes.has(mode);const moduleKey:LearningModuleKey=isListening?"listening":isReading?"reading":"writing";const module=moduleMeta(moduleKey).label;const meta=moduleMeta(moduleKey);const [seconds,setSeconds]=useState(0);const [running,setRunning]=useState(false);const [text,setText]=useState(()=>typeof window!=="undefined"?(window.localStorage.getItem(`ivy-study-${mode}`)??""):"");const [revealed,setRevealed]=useState(false);const [url,setUrl]=useState("");const [selected,setSelected]=useState("");const [materialIndex,setMaterialIndex]=useState(0);const [sessionVocabulary,setSessionVocabulary]=useState<string[]>([]);const [savedSessionId,setSavedSessionId]=useState("");const listening=listeningPool[materialIndex%listeningPool.length]!;const reading=isReading?sampleReading[mode as keyof typeof sampleReading]:null;const prompt=!isListening&&!isReading?writingPrompt[mode as "free-writing"|"journal"|"opinion"]:undefined;const wordCount=text.trim()?text.trim().split(/\s+/).filter(Boolean).length:0;
useEffect(()=>{if(!running)return;const id=window.setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(id)},[running]);useEffect(()=>{window.localStorage.setItem(`ivy-study-${mode}`,text)},[mode,text]);useEffect(()=>{setSavedSessionId("");setSeconds(0);setRunning(false);setSessionVocabulary([])},[mode]);
function capture(){const value=window.getSelection()?.toString().trim()??"";if(value.length>1&&value.length<80)setSelected(value)}function saveWord(){if(!selected)return;addVocabulary({word:selected,module,source:labels[mode],...(reading?.text?{context:reading.text}:{})});setSessionVocabulary(prev=>prev.includes(selected)?prev:[...prev,selected]);setSelected("");window.getSelection()?.removeAllRanges()}
function finish(){if(savedSessionId)return;setRunning(false);const score=module==="写作"?`${wordCount} words`:undefined;const sessionId=addSession({date:new Date().toISOString().slice(0,10),module,activity:labels[mode],tool:"Ivy Daily Workspace",durationMinutes:Math.max(1,Math.round(seconds/60)),...(score?{score}:{}),...(text.trim()?{notes:text.trim()}:{} )});saveSessionDetail({sessionId,kind:"daily",subtype:mode,completedAt:new Date().toISOString(),...(prompt?{prompt}:{}),...(isListening&&mode!=="video"?{sourceTitle:listening.title,sourceText:listening.text,mediaLabel:"Daily English audio"}:{}),...(mode==="video"&&url?{sourceTitle:"External listening material",mediaLabel:url}:{}),...(reading?{sourceTitle:reading.title,sourceText:reading.text}:{}),...(text.trim()?{userResponse:text.trim()}:{}),...(sessionVocabulary.length?{vocabulary:sessionVocabulary}:{}),metrics:{seconds,wordCount}});setSavedSessionId(sessionId)}
function another(){setSavedSessionId("");setSeconds(0);setRunning(false);setText("");setRevealed(false);setSessionVocabulary([]);window.localStorage.removeItem(`ivy-study-${mode}`)}
function shuffleMaterial(){setMaterialIndex(index=>(index+1)%listeningPool.length);setRevealed(false);setSavedSessionId("")}
return <div className="min-h-screen bg-[#f6f3ec] text-[#282b29]"><div className="mx-auto max-w-5xl px-5 py-6 sm:px-8"><header className="flex flex-wrap items-center justify-between gap-3"><Link to="/practice" search={{module:moduleKey}} className="inline-flex items-center gap-1.5 text-xs text-[#707770]"><ChevronLeft className="size-4"/>返回{module}学习</Link><div className="flex items-center gap-2"><Link to="/history" search={{module:moduleKey}} className="text-[11px] text-[#617067] underline underline-offset-4">历史</Link><Link to="/progress-detail" search={{module:moduleKey}} className="text-[11px] text-[#617067] underline underline-offset-4">进度</Link><a href={meta.examHref} className="inline-flex items-center gap-1 rounded-full bg-[#2e3e33] px-3 py-1.5 text-[11px] text-white"><ArrowUpRight className="size-3"/>模拟机考</a></div></header><main className="py-9"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.18em] text-[#788078]">Daily English</p><h1 className="mt-2 font-serif text-3xl">{labels[mode]}</h1></div><div className="flex items-center gap-2"><span className="font-mono text-sm">{format(seconds)}</span><button type="button" onClick={()=>setRunning(v=>!v)} className="flex size-9 items-center justify-center rounded-full border border-[#d1cec5] bg-white">{running?<Pause className="size-3.5"/>:<Play className="size-3.5"/>}</button><button type="button" onClick={()=>{setSeconds(0);setRunning(false)}} className="flex size-9 items-center justify-center rounded-full hover:bg-white"><RotateCcw className="size-3.5"/></button></div></div>
{savedSessionId?<section className="mt-7 rounded-2xl border border-[#b9cbbd] bg-[#eef5ef] p-5"><div className="flex items-start gap-3"><div className="flex size-9 items-center justify-center rounded-full bg-white text-[#42604a]"><Check className="size-4"/></div><div className="flex-1"><p className="text-sm font-medium">已保存到{module}历史</p><p className="mt-1 text-xs text-[#68746b]">{labels[mode]} · {Math.max(1,Math.round(seconds/60))} min{module==="写作"?` · ${wordCount} words`:""}{sessionVocabulary.length?` · ${sessionVocabulary.length} vocabulary`:""}</p><div className="mt-4 flex flex-wrap gap-2"><Link to="/session" search={{id:savedSessionId,from:"practice",module:moduleKey}} className="rounded-full bg-[#2e3e33] px-4 py-2 text-xs text-white">查看本次记录</Link><button type="button" onClick={another} className="rounded-full border border-[#b8c4ba] px-4 py-2 text-xs">再练一次</button><Link to="/practice" search={{module:moduleKey}} className="rounded-full border border-[#b8c4ba] px-4 py-2 text-xs">返回{module}</Link></div></div></div></section>:null}
{isListening?<section className="mt-8 grid gap-6 lg:grid-cols-[0.92fr_1.08fr]"><div className="rounded-3xl border border-[#dad6cc] bg-white p-6"><div className="flex items-center justify-between gap-3"><p className="text-sm">{mode==="video"?"外部听力素材":listening.title}</p>{mode!=="video"?<button type="button" onClick={shuffleMaterial} className="inline-flex items-center gap-1 rounded-full border border-[#d5d8d2] px-3 py-1.5 text-[11px]"><Shuffle className="size-3"/>换一段</button>:null}</div><p className="mt-3 text-sm leading-7 text-[#626963]">{mode==="video"?"贴一个你今天真正想看的视频或访谈链接，完成后把这次材料和笔记一起保存。":"播放器的操作方式和 CBT 保持一致：播放、暂停、前后跳、拖进度、重放、速度和音量都集中在这里。"}</p>{mode==="video"?<><Input value={url} onChange={e=>setUrl(e.target.value)} className="mt-5" placeholder="YouTube / B站 / 其他链接"/>{url?<a href={url} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs text-[#4d6b56]"><Link2 className="size-3"/>打开素材</a>:null}</>:<div className="mt-5"><DailyAudioPlayer text={listening.text} storageKey={`ivy-daily-audio-${mode}-${materialIndex}`} onPlayStateChange={setRunning}/>{mode==="dictation"?<Button variant="outline" className="mt-4 rounded-full" onClick={()=>setRevealed(v=>!v)}>{revealed?"隐藏原文":"对照原文"}</Button>:null}{revealed?<p className="mt-4 rounded-xl bg-[#f3f2ed] p-4 text-sm leading-6">{listening.text}</p>:null}</div>}</div><div className="rounded-3xl border border-[#dad6cc] bg-white p-6"><p className="text-xs text-[#777e78]">{mode==="dictation"?"你的听写":mode==="shadowing"?"跟读后的复盘":"学习笔记"}</p><Textarea value={text} onChange={e=>{setText(e.target.value);setSavedSessionId("")}} rows={12} className="mt-3 resize-none" placeholder="写下你听到的内容、难点或复盘..."/><Button onClick={finish} disabled={Boolean(savedSessionId)} className="mt-4 rounded-full">{savedSessionId?<><Check className="mr-2 size-4"/>已保存</>:<><Check className="mr-2 size-4"/>完成这次练习</>}</Button></div></section>:null}
{isReading&&reading?<section className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><article onMouseUp={capture} className="rounded-3xl border border-[#dad6cc] bg-white p-7 sm:p-9"><p className="text-xs text-[#7a817b]">Reading</p><h2 className="mt-2 font-serif text-2xl">{reading.title}</h2><p className="mt-6 text-[16px] leading-8">{reading.text}</p>{selected?<button type="button" onClick={saveWord} className="mt-5 inline-flex items-center gap-1.5 rounded-full border border-[#c8cfc8] px-3 py-1.5 text-xs"><Highlighter className="size-3.5"/>保存 “{selected}” 到生词本</button>:null}</article><aside className="rounded-3xl border border-[#dad6cc] bg-white p-6"><p className="text-xs text-[#777e78]">Notes</p><Textarea value={text} onChange={e=>{setText(e.target.value);setSavedSessionId("")}} rows={12} className="mt-3 resize-none" placeholder="摘要、想法、生词..."/><Button onClick={finish} disabled={Boolean(savedSessionId)} className="mt-4 rounded-full">{savedSessionId?<><Check className="mr-2 size-4"/>已保存</>:<><Save className="mr-2 size-4"/>保存并完成</>}</Button>{mode==="material"&&libraryItems.length?<div className="mt-6 border-t border-[#e2dfd6] pt-4"><p className="text-[11px] text-[#7a817b]">资料库最近添加</p>{libraryItems.slice(0,3).map(item=><p key={item.id} className="mt-2 truncate text-xs">{item.title}</p>)}</div>:null}</aside></section>:null}
{!isListening&&!isReading?<section className="mt-8 rounded-3xl border border-[#dad6cc] bg-white p-6 sm:p-8"><div className="flex items-start gap-3 rounded-xl bg-[#f4f3ee] p-4"><Sparkles className="mt-0.5 size-4 shrink-0 text-[#58705e]"/><p className="text-sm leading-6">{prompt}</p></div><Textarea value={text} onChange={e=>{setText(e.target.value);setSavedSessionId("")}} rows={18} className="mt-5 resize-none text-[15px] leading-7" placeholder="Start writing..."/><div className="mt-3 flex items-center justify-between"><span className="text-xs text-[#777e78]">{wordCount} words · 自动保存在本机</span><Button onClick={finish} disabled={Boolean(savedSessionId)} className="rounded-full">{savedSessionId?"已保存":"完成这次练习"}</Button></div></section>:null}</main></div></div>}
