import { useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Plus, Trash2 } from "lucide-react";
import { PageHeader, SectionTitle, Chip } from "@/components/ui-kit";
import { JournalPaper } from "@/components/journal-ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useAppState, type VocabularyStatus } from "@/state/app-state";
import type { Module } from "@/data/mock";
import { cn } from "@/lib/utils";

export const Route=createFileRoute("/vocabulary")({head:()=>({meta:[{title:"生词本 · Ivy English"}]}),component:VocabularyPage});
const modules:Module[]=["听力","口语","阅读","写作","词汇"];
const statuses:VocabularyStatus[]=["新词","复习中","已掌握"];
const subjectClass:Record<string,string>={听力:"subject-listening",口语:"subject-speaking",阅读:"subject-reading",写作:"subject-writing",词汇:""};
function VocabularyPage(){const {vocabulary,addVocabulary,updateVocabularyStatus,removeVocabulary}=useAppState();const [status,setStatus]=useState<"全部"|VocabularyStatus>("全部");const [word,setWord]=useState("");const [meaning,setMeaning]=useState("");const [context,setContext]=useState("");const [source,setSource]=useState("");const [module,setModule]=useState<Module>("阅读");const visible=useMemo(()=>status==="全部"?vocabulary:vocabulary.filter(item=>item.status===status),[status,vocabulary]);function save(){if(!word.trim())return;addVocabulary({word,...(meaning.trim()?{meaning:meaning.trim()}:{}),...(context.trim()?{context:context.trim()}:{}),source:source.trim()||"手动添加",module});setWord("");setMeaning("");setContext("");setSource("");}
return <div className="journal-page space-y-9"><div className="flex flex-wrap items-center justify-between gap-3"><Link to="/library" className="journal-link inline-flex items-center gap-1.5 text-xs"><ArrowLeft className="size-3.5"/>返回资料库</Link><Link to="/progress" className="journal-link text-xs">查看进度</Link></div><PageHeader title="生词本" subtitle="把阅读、听力和写作里真正遇到的词留下来，而不是背一份陌生词表。"/><JournalPaper tone="lavender" className="p-5 sm:p-6"><SectionTitle title="添加一个词"/><div className="grid gap-3 sm:grid-cols-2"><Input value={word} onChange={e=>setWord(e.target.value)} placeholder="word / phrase"/><Input value={meaning} onChange={e=>setMeaning(e.target.value)} placeholder="自己的释义（可选）"/><Input value={source} onChange={e=>setSource(e.target.value)} placeholder="来源，例如 Reading Passage 2"/><div className="flex gap-2 overflow-x-auto">{modules.map(m=><Chip key={m} active={module===m} onClick={()=>setModule(m)}>{m}</Chip>)}</div></div><Textarea value={context} onChange={e=>setContext(e.target.value)} rows={2} className="mt-3 resize-none" placeholder="原句 / 语境（可选）"/><Button onClick={save} className="journal-button mt-3 rounded-sm"><Plus className="mr-1 size-3.5"/>保存到生词本</Button></JournalPaper><section><SectionTitle title="我的词" subtitle={`${vocabulary.length} 个`}/><div className="mb-4 flex gap-2 overflow-x-auto">{(["全部",...statuses] as const).map(s=><Chip key={s} active={status===s} onClick={()=>setStatus(s)}>{s}</Chip>)}</div><div className="grid gap-4 md:grid-cols-2">{visible.map((item,index)=>{const theme=subjectClass[item.module]??"";return <article key={item.id} className={`${theme} journal-index-card p-5 pt-7 ${index%2===0?"md:-rotate-[0.2deg]":"md:rotate-[0.2deg]"}`}><div className="flex items-start justify-between gap-3"><div><p className="display text-xl text-[var(--journal-ink)]">{item.word}</p><p className="mt-1 text-[11px] text-[#63709A]">{item.module} · {item.source}</p></div><button type="button" onClick={()=>removeVocabulary(item.id)} className="text-[#63709A] hover:text-[var(--journal-danger)]"><Trash2 className="size-3.5"/></button></div>{item.meaning?<p className="mt-4 text-sm text-[var(--journal-body)]">{item.meaning}</p>:null}{item.context?<p className="journal-rule mt-3 border border-[color:var(--journal-line)] bg-[var(--journal-paper)] p-3 text-xs leading-7 text-[#52608C]">{item.context}</p>:null}<div className="mt-4 flex flex-wrap gap-2">{statuses.map(s=><button key={s} type="button" onClick={()=>updateVocabularyStatus(item.id,s)} className={cn("border px-2.5 py-1 text-[10px]",item.status===s?"border-[var(--journal-blue)] bg-[var(--journal-lavender)] text-[var(--journal-ink)]":"border-[var(--journal-line)] bg-[var(--journal-paper)] text-[#63709A]")}>{s}</button>)}</div></article>})}{!visible.length?<JournalPaper tone="paper" className="col-span-full py-12 text-center text-sm text-[#63709A]">这个筛选下还没有词。</JournalPaper>:null}</div></section></div>}
