import { useEffect, useRef, useState } from "react";
import { FastForward, FileAudio, Pause, Play, Rewind, RotateCcw, Upload, X } from "lucide-react";
import { useRouterState } from "@tanstack/react-router";

function format(seconds:number){const safe=Math.max(0,Math.floor(seconds||0));return `${Math.floor(safe/60).toString().padStart(2,"0")}:${(safe%60).toString().padStart(2,"0")}`}
export function ListeningRealAudioBridge(){
  const pathname=useRouterState({select:s=>s.location.pathname});
  const [url,setUrl]=useState<string|null>(null);const [name,setName]=useState("");const [duration,setDuration]=useState(0);const [time,setTime]=useState(0);const [playing,setPlaying]=useState(false);const [volume,setVolume]=useState(.9);const audioRef=useRef<HTMLAudioElement|null>(null);
  const enabled=pathname==="/listening-exam-v3"&&typeof window!=="undefined"&&new URLSearchParams(window.location.search).get("mode")!=="exam";
  const full=enabled&&new URLSearchParams(window.location.search).get("scope")==="full";
  useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);
  if(!enabled)return null;
  function choose(file:File|undefined){if(!file)return;window.speechSynthesis?.cancel();setUrl(prev=>{if(prev)URL.revokeObjectURL(prev);return URL.createObjectURL(file)});setName(file.name);setTime(0);setPlaying(false)}
  function toggle(){const audio=audioRef.current;if(!audio)return;if(audio.paused){void audio.play()}else audio.pause()}
  function seek(next:number){const audio=audioRef.current;if(!audio)return;audio.currentTime=Math.min(duration,Math.max(0,next));setTime(audio.currentTime)}
  function clear(){const audio=audioRef.current;audio?.pause();setUrl(prev=>{if(prev)URL.revokeObjectURL(prev);return null});setName("");setTime(0);setDuration(0);setPlaying(false)}
  if(!url)return <label className="fixed bottom-5 left-5 z-[110] hidden cursor-pointer items-center gap-2 rounded-full border border-[#b9b9b9] bg-white px-4 py-2 text-[11px] text-[#3f4c45] shadow-lg lg:flex"><Upload className="size-3.5"/>载入真实听力音频<input type="file" accept="audio/*,.mp3,.m4a,.wav,.ogg" className="hidden" onChange={e=>choose(e.target.files?.[0])}/></label>;
  return <div className="fixed left-0 right-0 z-[105] hidden border-b border-[#aaa] bg-white px-5 py-3 shadow-sm lg:block" style={{top:full?102:58}}><audio ref={audioRef} src={url} preload="metadata" onLoadedMetadata={e=>{setDuration(e.currentTarget.duration||0);e.currentTarget.volume=volume}} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)}/><div className="flex items-center gap-3"><div className="flex size-9 shrink-0 items-center justify-center rounded-full bg-[#eaf1ed] text-[#466153]"><FileAudio className="size-4"/></div><div className="min-w-0 flex-1"><div className="mb-1 flex items-center justify-between gap-3 text-[10px] text-[#666]"><span className="truncate">真实音频 · {name}</span><span className="shrink-0">{format(time)} / {format(duration)}</span></div><input type="range" min={0} max={Math.max(1,duration)} step="0.1" value={Math.min(time,Math.max(1,duration))} onChange={e=>seek(Number(e.target.value))} className="block h-4 w-full cursor-pointer accent-[#557b92]" aria-label="真实音频播放进度"/></div><div className="flex items-center gap-1.5"><button type="button" onClick={()=>seek(time-5)} className="flex h-9 items-center gap-1 rounded-sm border border-[#bbb] px-2 text-[10px]"><Rewind className="size-3.5"/>5s</button><button type="button" onClick={toggle} className="flex h-9 items-center gap-1 rounded-sm border border-[#557b92] bg-[#eef5f8] px-3 text-[11px] text-[#264f67]">{playing?<><Pause className="size-3.5"/>暂停</>:<><Play className="size-3.5"/>播放</>}</button><button type="button" onClick={()=>seek(time+5)} className="flex h-9 items-center gap-1 rounded-sm border border-[#bbb] px-2 text-[10px]">5s<FastForward className="size-3.5"/></button><button type="button" onClick={()=>{seek(0);void audioRef.current?.play()}} className="flex h-9 items-center gap-1 rounded-sm border border-[#bbb] px-2 text-[10px]"><RotateCcw className="size-3.5"/>重放</button><input type="range" min="0" max="1" step="0.05" value={volume} onChange={e=>{const value=Number(e.target.value);setVolume(value);if(audioRef.current)audioRef.current.volume=value}} className="ml-2 w-20" aria-label="真实音频音量"/><label className="flex h-9 cursor-pointer items-center rounded-sm border border-[#bbb] px-2 text-[10px]">换音频<input type="file" accept="audio/*,.mp3,.m4a,.wav,.ogg" className="hidden" onChange={e=>choose(e.target.files?.[0])}/></label><button type="button" onClick={clear} className="flex size-8 items-center justify-center text-[#777]" aria-label="关闭真实音频"><X className="size-3.5"/></button></div></div></div>;
}
