import type { ReactNode } from "react";
import { cn } from "@/lib/utils";
import type { SignalStatus } from "@/data/mock";

export function PageHeader({ title, subtitle, action }: { title: string; subtitle?: string; action?: ReactNode }) { return <header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h1 className="display text-3xl sm:text-4xl">{title}</h1>{subtitle ? <p className="mt-2 max-w-xl text-sm leading-relaxed text-muted-foreground">{subtitle}</p> : null}</div>{action}</header>; }
export function SectionTitle({ title, subtitle, action }: { title: string; subtitle?: string; action?: ReactNode }) { return <div className="mb-4 flex flex-wrap items-baseline justify-between gap-2"><div><h2 className="text-lg">{title}</h2>{subtitle ? <p className="mt-1 text-xs text-muted-foreground">{subtitle}</p> : null}</div>{action}</div>; }
export function StatusPill({ status }: { status: SignalStatus | string }) { const tone = status === "正在进步" ? "bg-sage-soft text-sage-foreground border-transparent" : status === "已稳定" ? "bg-secondary text-secondary-foreground border-transparent" : "bg-transparent text-muted-foreground border-border"; return <span className={cn("inline-flex shrink-0 items-center rounded-full border px-2.5 py-0.5 text-[11px] tracking-wide", tone)}>{status}</span>; }
export function Meta({ label, value }: { label: string; value: ReactNode }) { return <div><p className="text-[11px] text-muted-foreground">{label}</p><p className="mt-0.5 text-sm">{value}</p></div>; }
export function Callout({ children }: { children: ReactNode }) { return <div className="rounded-xl border border-border bg-secondary/60 px-4 py-3 text-xs leading-relaxed text-muted-foreground">{children}</div>; }
export function formatCnDate(iso: string) { const [, m, d] = iso.split("-"); return `${Number(m)}月${Number(d)}日`; }
export function MiniBars({ data }: { data: { label: string; minutes: number }[] }) { const max = Math.max(...data.map((d) => d.minutes), 1); return <div className="space-y-3">{data.map((d) => <div key={d.label} className="flex items-center gap-3"><span className="w-10 shrink-0 text-xs text-muted-foreground">{d.label}</span><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-sage transition-all duration-500" style={{ width: `${Math.max((d.minutes / max) * 100, 2)}%` }} /></div><span className="w-14 shrink-0 text-right text-xs tabular-nums text-muted-foreground">{d.minutes} min</span></div>)}</div>; }
export function TrendChart({ data }: { data: { label: string; minutes: number }[] }) { const max = Math.max(...data.map((d) => d.minutes), 1); return <div className="flex items-end gap-2 sm:gap-3">{data.map((d) => <div key={d.label} className="flex flex-1 flex-col items-center gap-2"><div className="flex h-32 w-full items-end justify-center"><div className="w-full max-w-14 rounded-t-md bg-sage/70 transition-all duration-500" style={{ height: `${Math.max((d.minutes / max) * 128, 3)}px` }} title={`${d.minutes} min`} /></div><span className="text-[10px] text-muted-foreground">{d.label}</span></div>)}</div>; }
export function Chip({ active, children, onClick }: { active?: boolean; children: ReactNode; onClick?: () => void }) { return <button type="button" onClick={onClick} className={cn("shrink-0 rounded-full border px-3 py-1.5 text-xs transition-colors", active ? "border-transparent bg-primary text-primary-foreground" : "border-border bg-card text-muted-foreground hover:border-sage hover:text-foreground")}>{children}</button>; }